"use client";

import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive, ArrowLeft, ExternalLink, Save, Send } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";

import { api, PUBLIC_WEB_URL, type ResourceRecord } from "../lib/api";
import { useAuth } from "./auth-provider";

type Values = { slug: string; primaryEmirate: string; otherPresence: string; selectedProjects: string; officialWebsite: string; sourceUrl: string; additionalSourceUrls: string; verificationDate: string; enquiryTypes: string; featured: boolean; displayOrder: string; nameEn: string; nameAr: string; descriptionEn: string; descriptionAr: string; focusEn: string; focusAr: string; noteEn: string; noteAr: string };
const empty: Values = { slug: "", primaryEmirate: "Dubai", otherPresence: "", selectedProjects: "", officialWebsite: "", sourceUrl: "", additionalSourceUrls: "", verificationDate: "", enquiryTypes: "new-booking\nprimary-sale\nresale", featured: false, displayOrder: "0", nameEn: "", nameAr: "", descriptionEn: "", descriptionAr: "", focusEn: "", focusAr: "", noteEn: "", noteAr: "" };
const lines = (value: string) => value.split("\n").map((item) => item.trim()).filter(Boolean);

export function DeveloperEditor({ id }: Readonly<{ id?: string }>) {
  const { user } = useAuth(); const router = useRouter(); const queryClient = useQueryClient(); const [notice, setNotice] = useState("");
  const record = useQuery({ queryKey: ["developer", id], queryFn: () => api<ResourceRecord>(`/admin/developers/${id}`), enabled: Boolean(id) });
  const { register, handleSubmit, reset, setError, formState: { errors, isSubmitting } } = useForm<Values>({ defaultValues: empty });
  useEffect(() => { if (!record.data) return; const data = record.data; const translations = data.translations as Record<string, Record<string, unknown>>; reset({ slug: String(data.slug ?? ""), primaryEmirate: String(data.primary_emirate ?? "Dubai"), otherPresence: ((data.other_presence ?? []) as string[]).join("\n"), selectedProjects: ((data.selected_projects ?? []) as string[]).join("\n"), officialWebsite: String(data.official_website ?? ""), sourceUrl: String(data.source_url ?? ""), additionalSourceUrls: ((data.additional_source_urls ?? []) as string[]).join("\n"), verificationDate: String(data.verification_date ?? ""), enquiryTypes: ((data.enquiry_types ?? []) as string[]).join("\n"), featured: Boolean(data.featured), displayOrder: String(data.display_order ?? 0), nameEn: String(translations.en?.name ?? ""), nameAr: String(translations.ar?.name ?? ""), descriptionEn: String(translations.en?.description ?? ""), descriptionAr: String(translations.ar?.description ?? ""), focusEn: String(translations.en?.focus ?? ""), focusAr: String(translations.ar?.focus ?? ""), noteEn: String(translations.en?.verification_note ?? ""), noteAr: String(translations.ar?.verification_note ?? "") }); }, [record.data, reset]);
  async function save(values: Values, status: "draft" | "published" | "archived") { setNotice(""); const payload = { slug: values.slug, primary_emirate: values.primaryEmirate, other_presence: lines(values.otherPresence), selected_projects: lines(values.selectedProjects), official_website: values.officialWebsite, source_url: values.sourceUrl, additional_source_urls: lines(values.additionalSourceUrls), verification_date: values.verificationDate, enquiry_types: lines(values.enquiryTypes), featured: values.featured, display_order: Number(values.displayOrder), status, translations: { en: { name: values.nameEn, description: values.descriptionEn, focus: values.focusEn, verification_note: values.noteEn }, ar: { name: values.nameAr, description: values.descriptionAr, focus: values.focusAr, verification_note: values.noteAr } } }; try { const saved = await api<ResourceRecord>(id ? `/admin/developers/${id}` : "/admin/developers", { method: id ? "PUT" : "POST", body: JSON.stringify(payload) }, user?.csrf_token); await queryClient.invalidateQueries({ queryKey: ["developers"] }); setNotice(status === "published" ? "Developer published." : status === "archived" ? "Developer archived." : "Draft saved."); if (!id) router.replace(`/developers/${saved.id}`); } catch (reason) { setError("root", { message: reason instanceof Error ? reason.message : "Save failed." }); } }
  const submit = (status: "draft" | "published" | "archived") => handleSubmit((values) => save(values, status));
  if (id && record.isLoading) return <div className="panel-state">Loading developer…</div>; if (record.error) return <div className="panel-state form-error" role="alert">{record.error.message}</div>;
  const published = record.data?.status === "published";
  return <section><div className="page-heading"><div><Link className="back-link" href="/developers"><ArrowLeft aria-hidden size={16}/>Back to developers</Link><h1>{id ? "Edit developer" : "New developer"}</h1><p>Publication requires complete English, Arabic and provenance fields.</p></div>{published ? <a className="primary-button" href={`${PUBLIC_WEB_URL}/en/developers#${record.data?.slug}`} rel="noreferrer" target="_blank">View on website<ExternalLink aria-hidden size={16}/></a> : null}</div>
    <form className="editor-form" onSubmit={submit("draft")}>{errors.root?.message ? <div className="form-error" role="alert">{errors.root.message}</div> : null}{notice ? <div className="form-success" role="status">{notice}</div> : null}
      <fieldset><legend>Identity and publication</legend><div className="form-grid"><label>Stable slug<input {...register("slug")} pattern="[a-z0-9]+(?:-[a-z0-9]+)*" required/></label><label>Primary emirate<input {...register("primaryEmirate")} required/></label><label>Other market presence (one per line)<textarea rows={3} {...register("otherPresence")}/></label><label>Selected project identity references (one per line)<textarea rows={3} {...register("selectedProjects")}/></label><label className="check"><input type="checkbox" {...register("featured")}/>Featured</label><label>Display order<input min="0" type="number" {...register("displayOrder")} required/></label></div></fieldset>
      <fieldset><legend>English content</legend><div className="form-grid"><label>Official name<input {...register("nameEn")} required/></label><label>Development focus<input {...register("focusEn")} required/></label><label className="wide">Description<textarea rows={5} {...register("descriptionEn")} required/></label><label className="wide">Verification note<textarea rows={3} {...register("noteEn")} required/></label></div></fieldset>
      <fieldset dir="rtl"><legend>المحتوى العربي</legend><div className="form-grid"><label>الاسم الرسمي<input {...register("nameAr")} required/></label><label>مجال التطوير<input {...register("focusAr")} required/></label><label className="wide">الوصف<textarea rows={5} {...register("descriptionAr")} required/></label><label className="wide">ملاحظة التحقق<textarea rows={3} {...register("noteAr")} required/></label></div></fieldset>
      <fieldset><legend>Provenance</legend><div className="form-grid"><label>Official website<input type="url" {...register("officialWebsite")} required/></label><label>Primary source URL<input type="url" {...register("sourceUrl")} required/></label><label>Verification date<input type="date" {...register("verificationDate")} required/></label><label>Enquiry types (one per line)<textarea rows={3} {...register("enquiryTypes")} required/></label><label className="wide">Additional official source URLs (one per line)<textarea rows={3} {...register("additionalSourceUrls")}/></label></div></fieldset>
      <div className="form-actions developer-actions"><button className="action-button" disabled={isSubmitting} type="submit"><Save aria-hidden size={17}/>Save draft</button><button className="action-button action-button--publish" disabled={isSubmitting} onClick={submit("published")} type="button"><Send aria-hidden size={17}/>Publish</button>{id ? <button className="action-button action-button--archive" disabled={isSubmitting} onClick={submit("archived")} type="button"><Archive aria-hidden size={17}/>Archive</button> : null}</div>
    </form></section>;
}
