"use client";

import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, ExternalLink, SearchCheck } from "lucide-react";
import Image from "next/image";
import { useRouter } from "next/navigation";

import { API_URL, api, type PageResponse } from "../lib/api";
import { AdminPageHeader, DataTableShell, EmptyState, InlineFeedback, LoadingState, StatusBadge } from "./admin-ui";
import { useAuth } from "./auth-provider";
import { GuardedLink } from "./navigation-guard";

type ImportBatch = { id: string; name: string; source_reference: string; started_at?: string | null; completed_at?: string | null; total_count: number; clean_count: number; needs_review_count: number; failed_count: number };
type Option = { id: string; slug?: string; name_en?: string; translations?: { en?: { name?: string } } };
type Eligibility = Record<string, boolean>;
type CandidateSummary = { id: string; manifest_row_id: number; project_name: string; owner_developer: string; owner_area: string; proposed_developer_id?: string | null; proposed_area_id?: string | null; official_source_url?: string | null; review_status: string; processing_status: string; last_successful_stage?: string | null; processing_eligibility_errors: string[]; missing_fields: string[]; blockers: string[]; warnings: string[]; conflict_count: number; media_count: number; media_downloaded_count: number; media_failed_count: number; last_verified_at?: string | null; review_version: number; human_review_completed: boolean; arabic_review_state: string; rights_status: string; eligibility: Eligibility };
type CandidateInfo = Pick<CandidateSummary, "project_name" | "owner_developer" | "owner_area" | "review_status" | "eligibility" | "processing_eligibility_errors">;
type BatchDetail = ImportBatch & { metrics: Record<string, number>; candidates: CandidateSummary[]; candidate_meta: { page: number; page_size: number; total: number; pages: number }; filtered_candidate_ids: string[]; filtered_candidate_versions: Record<string, number>; filtered_candidate_info: Record<string, CandidateInfo>; all_candidate_ids: string[]; all_candidate_versions: Record<string, number>; all_candidate_info: Record<string, CandidateInfo> };
type CandidateMedia = { id: string; category: string; source_url: string; rights_status: string; rights_basis?: string | null; stage_status: string; has_thumbnail: boolean; has_full_preview: boolean; mime_type?: string | null; quality_status: string; public_eligible: boolean; cover_eligible: boolean; width?: number; height?: number; size_bytes?: number; duplicate_of_id?: string | null; retrieved_at?: string | null; failure_reason?: string | null; normalized_filename?: string | null; display_order: number; alt_en_draft?: string | null; alt_ar_draft?: string | null; title_en?: string | null; title_ar?: string | null; description_en?: string | null; description_ar?: string | null; tags?: string[]; derivatives: Array<Record<string, unknown>>; change_status: string };
type CandidateDetail = CandidateSummary & { batch_id: string; owner_manifest_values: Record<string, unknown>; normalized_payload: Record<string, unknown> | null; raw_source_payload: Record<string, unknown>; source_urls: string[]; arabic_review_required: boolean; acquisition_summary: Record<string, unknown>; match_result: Record<string, unknown> | null; validation_errors: unknown[]; conflict_reasons: string[]; eligibility_errors: string[]; automatic_recovery_needs_review: boolean; evidence: Array<Record<string, unknown>>; media_summary: { total_acquired: number; approved: number; removed: number }; staged_media: CandidateMedia[]; changes: Array<Record<string, unknown>>; human_edited_fields: string[]; editorial_draft: { overview_en?: string | null; overview_ar?: string | null; source_version: string; model_name?: string | null; model_version?: string | null; origin?: string | null; overview_pack_id?: string | null; fact_input_hash?: string | null; candidate_version?: number | null; approval_status: string } | null; overview_provider: { state: string; message: string; required_environment_variables: string[] }; overview_generation: { state: string; fact_guard_result: Record<string, unknown>; generated_at: string; approval_status: string } | null; content_hash: string; adapter_key?: string | null; adapter_version?: string | null };
type OverviewPack = { id: string; pack_version: string; status: string; pack_hash: string; selected_count: number; eligible_count: number; ineligible_count: number; imported_count: number; failed_count: number; created_at: string; imported_at?: string | null; explanation: string; items: Array<{ candidate_id: string; candidate_version: number; eligible: boolean; status: string; exclusion_reasons: string[]; failure_code?: string | null; failure_message?: string | null }> };
type Filters = { q: string; status: string; developer: string; area: string; areaMapping: string; source: string; missing: string; conflicts: string; media: string; arabic: string; sort: string; direction: string; page: number };
type PendingAction = { action: string; label: string; destructive?: boolean; processing?: boolean; selectionMode?: string } | null;

const initialFilters: Filters = { q: "", status: "", developer: "", area: "", areaMapping: "", source: "", missing: "", conflicts: "", media: "", arabic: "", sort: "row", direction: "asc", page: 1 };

export function ProjectImportList() {
  const query = useQuery({ queryKey: ["project-imports"], queryFn: () => api<PageResponse<ImportBatch>>("/admin/project-imports") });
  return <section><AdminPageHeader description="Review staged evidence before any candidate can become a canonical Project. This queue never publishes automatically." eyebrow="Off-Plan CMS" title="Project Imports"/>{query.isLoading ? <LoadingState label="Loading import batches…"/> : query.error ? <InlineFeedback tone="error">{query.error.message}</InlineFeedback> : !query.data?.items.length ? <DataTableShell label="Project import batches"><EmptyState description="No import batch exists. The owner manifest remains an inert intake file." title="No Project imports yet"/></DataTableShell> : <DataTableShell label="Project import batches"><table><thead><tr><th>Batch</th><th>Source</th><th>Total</th><th>Needs Review</th><th>Failed</th><th>Started</th><th>Action</th></tr></thead><tbody>{query.data.items.map((batch) => <tr key={batch.id}><td><strong>{batch.name}</strong></td><td>{batch.source_reference}</td><td>{batch.total_count}</td><td>{batch.needs_review_count}</td><td>{batch.failed_count}</td><td>{date(batch.started_at)}</td><td><GuardedLink className="table-link" href={`/project-imports/${batch.id}`}><SearchCheck aria-hidden size={15}/>Review batch</GuardedLink></td></tr>)}</tbody></table></DataTableShell>}</section>;
}

export function ProjectImportDetail({ id }: Readonly<{ id: string }>) {
  const { user } = useAuth();
  const router = useRouter();
  const queryClient = useQueryClient();
  const [filters, setFilters] = useState(initialFilters);
  const [selected, setSelected] = useState<Record<string, number>>({});
  const [pending, setPending] = useState<PendingAction>(null);
  const [developer, setDeveloper] = useState("");
  const [area, setArea] = useState("");
  const [reason, setReason] = useState("");
  const [selectionMode, setSelectionMode] = useState("manual");
  const [responseFile, setResponseFile] = useState<File | null>(null);
  const [workspaceRestored, setWorkspaceRestored] = useState(false);
  useEffect(() => {
    const saved = window.sessionStorage.getItem(`project-import-workspace:${id}`);
    const timer = window.setTimeout(() => {
      if (saved) {
        try {
          const state = JSON.parse(saved) as { filters?: Filters; selected?: Record<string, number>; selectionMode?: string };
          if (state.filters) setFilters(state.filters);
          if (state.selected) setSelected(state.selected);
          if (state.selectionMode) setSelectionMode(state.selectionMode);
        } catch { window.sessionStorage.removeItem(`project-import-workspace:${id}`); }
      }
      setWorkspaceRestored(true);
    }, 0);
    return () => window.clearTimeout(timer);
  }, [id]);
  useEffect(() => {
    if (workspaceRestored) window.sessionStorage.setItem(`project-import-workspace:${id}`, JSON.stringify({ filters, selected, selectionMode }));
  }, [filters, id, selected, selectionMode, workspaceRestored]);
  const params = useMemo(() => { const value = new URLSearchParams({ page: String(filters.page), page_size: "25", sort: filters.sort, direction: filters.direction }); if (filters.q) value.set("q", filters.q); if (filters.status) value.set("review_status", filters.status); if (filters.developer) value.set("developer_id", filters.developer); if (filters.area) value.set("area_id", filters.area); if (filters.areaMapping) value.set("area_mapping", filters.areaMapping); if (filters.source) value.set("official_source", filters.source); if (filters.missing) value.set("missing_evidence", filters.missing); if (filters.conflicts) value.set("has_conflicts", filters.conflicts); if (filters.media) value.set("media_status", filters.media); if (filters.arabic) value.set("arabic_review", filters.arabic); return value.toString(); }, [filters]);
  const query = useQuery({ queryKey: ["project-import", id, params], queryFn: () => api<BatchDetail>(`/admin/project-imports/${id}?${params}`) });
  const developers = useQuery({ queryKey: ["import-developers"], queryFn: () => api<PageResponse<Option>>("/admin/developers?page_size=100") });
  const areas = useQuery({ queryKey: ["import-areas"], queryFn: () => api<PageResponse<Option>>("/admin/areas?page_size=100") });
  const packs = useQuery({ queryKey: ["overview-packs", id], queryFn: () => api<PageResponse<OverviewPack>>(`/admin/project-imports/${id}/overview-packs`) });
  const bulk = useMutation({ mutationFn: (action: string) => api<{ message: string }>(`/admin/project-imports/${id}/bulk`, { method: "POST", body: JSON.stringify({ action, candidate_ids: Object.keys(selected), expected_versions: selected, idempotency_key: crypto.randomUUID(), developer_id: action === "assign-developer" ? developer : null, area_id: action === "assign-area" ? area : null, rejection_reason: action === "reject" ? reason : null }) }, user?.csrf_token), onSuccess: () => { setSelected({}); setPending(null); setReason(""); void queryClient.invalidateQueries({ queryKey: ["project-import", id] }); } });
  const processing = useMutation({ mutationFn: () => api<{ id: string }>(`/admin/project-imports/${id}/processing-jobs`, { method: "POST", body: JSON.stringify({ requested_action: "clean-and-prepare", selection_mode: selectionMode, candidate_ids: Object.keys(selected), idempotency_key: crypto.randomUUID() }) }, user?.csrf_token), onSuccess: (job) => { setPending(null); router.push(`/project-processing/${job.id}`); } });
  const preparePack = useMutation({ mutationFn: () => api<OverviewPack>(`/admin/project-imports/${id}/overview-packs`, { method: "POST", body: JSON.stringify({ selection_mode: selectionMode, candidate_ids: Object.keys(selected), expected_versions: selected, idempotency_key: crypto.randomUUID() }) }, user?.csrf_token), onSuccess: () => { setSelected({}); void queryClient.invalidateQueries({ queryKey: ["overview-packs", id] }); } });
  const latestPack = packs.data?.items[0];
  const importPack = useMutation({ mutationFn: () => { if (!latestPack || !responseFile) throw new Error("Choose a completed JSON response file."); const body = new FormData(); body.set("response_file", responseFile); return api<{ imported: number; failed: number }>(`/admin/project-overview-packs/${latestPack.id}/import`, { method: "POST", body }, user?.csrf_token); }, onSuccess: () => { setResponseFile(null); void queryClient.invalidateQueries({ queryKey: ["overview-packs", id] }); void queryClient.invalidateQueries({ queryKey: ["project-import", id] }); } });
  const downloadPack = async (pack: OverviewPack) => { const response = await fetch(`${API_URL}/admin/project-overview-packs/${pack.id}/download`, { method: "POST", credentials: "include", headers: { "X-CSRF-Token": user?.csrf_token ?? "" } }); if (!response.ok) throw new Error("Private pack download failed."); const blob = await response.blob(); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `overview-pack-${pack.id}.json`; anchor.click(); URL.revokeObjectURL(url); };
  const updateFilter = (key: keyof Filters, value: string | number) => setFilters((current) => ({ ...current, [key]: value, page: key === "page" ? Number(value) : 1 }));
  if (query.isLoading) return <LoadingState label="Loading import review…"/>;
  if (query.error) return <InlineFeedback tone="error">{query.error.message}</InlineFeedback>;
  if (!query.data) return null;
  const batch = query.data;
  const allPageSelected = batch.candidates.length > 0 && batch.candidates.every((item) => selected[item.id] === item.review_version);
  const selectedCount = Object.keys(selected).length;
  const selectedInfo = Object.keys(selected).map((candidateId) => batch.all_candidate_info[candidateId]).filter(Boolean);
  const selectedOutsidePage = selectedCount - batch.candidates.filter((item) => selected[item.id] === item.review_version).length;
  const actionCounts = (action: string) => ({ eligible: selectedInfo.filter((item) => item.eligibility[action]).length, blocked: selectedInfo.filter((item) => !item.eligibility[action]).length });
  const processingEligible = selectedInfo.filter((item) => item.processing_eligibility_errors.length === 0).length;
  const processingBlocked = selectedCount - processingEligible;
  return <section className="import-workspace"><AdminPageHeader back={<GuardedLink className="back-link" href="/project-imports"><ArrowLeft aria-hidden size={16}/>Back to Project Imports</GuardedLink>} description={batch.source_reference} eyebrow="Import Review Queue" title={batch.name}/>
    <div className="status-summary import-metrics" aria-label="Batch status filters">{[["all", "All"], ["needs-review", "Needs Review"], ["failed", "Failed"], ["ready-for-approval", "Ready"], ["rejected", "Rejected"], ["merged", "Draft created"]].map(([value, label]) => <button aria-pressed={(filters.status || "all") === value} key={value} onClick={() => updateFilter("status", value === "all" ? "" : value)} type="button"><strong>{batch.metrics[value] ?? 0}</strong><span>{label}</span></button>)}</div>
    <div className="panel import-filters"><label className="wide">Search candidates<input placeholder="Project, Developer, Area or row" value={filters.q} onChange={(event) => updateFilter("q", event.target.value)}/></label><Filter label="Status" value={filters.status} onChange={(value) => updateFilter("status", value)} options={["needs-review", "failed", "ready-for-approval", "rejected", "merged"]}/><SelectOption label="Developer" value={filters.developer} onChange={(value) => updateFilter("developer", value)} records={developers.data?.items ?? []}/><SelectOption label="Area" value={filters.area} onChange={(value) => updateFilter("area", value)} records={areas.data?.items ?? []}/><Filter label="Area mapping" value={filters.areaMapping} onChange={(value) => updateFilter("areaMapping", value)} options={["mapped", "unmapped"]}/><Filter label="Official source" value={filters.source} onChange={(value) => updateFilter("source", value)} options={["available", "missing"]}/><Filter label="Missing evidence" value={filters.missing} onChange={(value) => updateFilter("missing", value)} options={["true", "false"]}/><Filter label="Conflicts" value={filters.conflicts} onChange={(value) => updateFilter("conflicts", value)} options={["true", "false"]}/><Filter label="Media" value={filters.media} onChange={(value) => updateFilter("media", value)} options={["reference-only", "downloaded", "duplicate", "failed"]}/><Filter label="Arabic review" value={filters.arabic} onChange={(value) => updateFilter("arabic", value)} options={["reviewed", "review-required"]}/><Filter label="Sort" value={filters.sort} onChange={(value) => updateFilter("sort", value)} options={["row", "project", "status", "last-checked"]}/><Filter label="Direction" value={filters.direction} onChange={(value) => updateFilter("direction", value)} options={["asc", "desc"]}/><button className="secondary-button" onClick={() => { setFilters(initialFilters); setSelected({}); }} type="button">Reset filters</button></div>
    {bulk.error || processing.error || preparePack.error || importPack.error ? <InlineFeedback tone="error">{bulk.error?.message ?? processing.error?.message ?? preparePack.error?.message ?? importPack.error?.message}</InlineFeedback> : null}
    <div className="selection-controls"><label><input checked={allPageSelected} onChange={(event) => { setSelectionMode("current-page"); setSelected((current) => { const next = { ...current }; batch.candidates.forEach((item) => { if (event.target.checked) next[item.id] = item.review_version; else delete next[item.id]; }); return next; }); }} type="checkbox"/>Select this page</label><button className="table-link" onClick={() => { setSelectionMode("first-25"); setSelected(Object.fromEntries(batch.filtered_candidate_ids.slice(0, 25).map((candidateId) => [candidateId, batch.filtered_candidate_versions[candidateId]]))); }} type="button">Select first 25</button><button className="table-link" onClick={() => { setSelectionMode("first-50"); setSelected(Object.fromEntries(batch.filtered_candidate_ids.slice(0, 50).map((candidateId) => [candidateId, batch.filtered_candidate_versions[candidateId]]))); }} type="button">Select first 50</button><button className="table-link" onClick={() => { setSelectionMode("all-filtered"); setSelected(batch.filtered_candidate_versions); }} type="button">Select all {batch.candidate_meta.total} filtered</button><button className="table-link" onClick={() => { setSelectionMode("complete-batch"); setSelected(batch.all_candidate_versions); }} type="button">Select complete batch</button>{selectedCount ? <button className="table-link" onClick={() => { setSelected({}); setSelectionMode("manual"); }} type="button">Clear selection</button> : null}</div>
    {!batch.candidates.length ? <DataTableShell label="Import candidates"><EmptyState description="No candidates match these filters." title="No matching candidates"/></DataTableShell> : <DataTableShell label="Import candidates"><table className="import-review-table"><thead><tr><th><span className="sr-only">Select</span></th><th>Row</th><th>Project</th><th>Developer</th><th>Area</th><th>Source</th><th>Review</th><th>Processing</th><th>Missing</th><th>Conflicts</th><th>Media</th><th>Last checked</th><th className="candidate-action-column">Action</th></tr></thead><tbody>{batch.candidates.map((item) => <tr key={item.id}><td data-label="Select"><input aria-label={`Select manifest row ${item.manifest_row_id}`} checked={selected[item.id] === item.review_version} onChange={(event) => { setSelectionMode(selectedOutsidePage > 0 ? "cross-page" : "manual"); setSelected((current) => { const next = { ...current }; if (event.target.checked) next[item.id] = item.review_version; else delete next[item.id]; return next; }); }} type="checkbox"/></td><td data-label="Row">{item.manifest_row_id}</td><td data-label="Project"><GuardedLink className="candidate-name-link" href={`/project-imports/${id}/candidates/${item.id}`}>{item.project_name}</GuardedLink></td><td data-label="Developer">{optionName(developers.data?.items, item.proposed_developer_id) ?? item.owner_developer}</td><td data-label="Area">{optionName(areas.data?.items, item.proposed_area_id) ?? item.owner_area}</td><td data-label="Source">{item.official_source_url ? <a aria-label={`Open official source for ${item.project_name}`} href={item.official_source_url} rel="noreferrer" target="_blank"><ExternalLink aria-hidden size={15}/></a> : "—"}</td><td data-label="Review"><StatusBadge status={item.review_status}/></td><td data-label="Processing"><StatusBadge status={item.processing_status}/></td><td data-label="Missing">{item.missing_fields.length}</td><td data-label="Conflicts">{item.conflict_count}</td><td data-label="Media">{item.media_downloaded_count}/{item.media_count}{item.media_failed_count ? ` (${item.media_failed_count} failed)` : ""}</td><td data-label="Last checked">{date(item.last_verified_at)}</td><td className="candidate-action-column" data-label="Action"><GuardedLink className="table-link candidate-review-link" href={`/project-imports/${id}/candidates/${item.id}`}>Review candidate</GuardedLink></td></tr>)}</tbody></table></DataTableShell>}
    <div className="pagination"><button disabled={filters.page <= 1} onClick={() => updateFilter("page", filters.page - 1)} type="button">Previous</button><span>Page {batch.candidate_meta.page} of {batch.candidate_meta.pages}</span><button disabled={filters.page >= batch.candidate_meta.pages} onClick={() => updateFilter("page", filters.page + 1)} type="button">Next</button></div>
    {selectedCount ? <div className="bulk-toolbar" role="region" aria-label="Bulk actions"><strong>{selectedCount} selected{selectedOutsidePage > 0 ? ` · ${selectedOutsidePage} outside this page` : ""}</strong><button disabled={preparePack.isPending || selectedCount > 50} onClick={() => preparePack.mutate()} type="button">Prepare Codex Overview Pack<small>Maximum 50 · private and review-gated</small></button><button onClick={() => setPending({ action: "clean-and-prepare", label: "Clean and prepare", processing: true, selectionMode })} type="button">Clean and prepare<small>{processingEligible} eligible{processingBlocked ? `, ${processingBlocked} ineligible` : ""}</small></button><select aria-label="Developer for selected candidates" value={developer} onChange={(event) => setDeveloper(event.target.value)}><option value="">Assign Developer…</option>{developers.data?.items.map((item) => <option key={item.id} value={item.id}>{recordName(item)}</option>)}</select><ActionButton action="assign-developer" counts={actionCounts("assign-developer")} disabled={!developer} label="Apply Developer" setPending={setPending}/><select aria-label="Area for selected candidates" value={area} onChange={(event) => setArea(event.target.value)}><option value="">Assign Area…</option>{areas.data?.items.map((item) => <option key={item.id} value={item.id}>{recordName(item)}</option>)}</select><ActionButton action="assign-area" counts={actionCounts("assign-area")} disabled={!area} label="Apply Area" setPending={setPending}/><ActionButton action="return-to-review" counts={actionCounts("return-to-review")} label="Return to Review" setPending={setPending}/><ActionButton action="mark-ready" counts={actionCounts("mark-ready")} label="Mark Ready" setPending={setPending}/><ActionButton action="create-drafts" counts={actionCounts("create-drafts")} destructive label="Create Drafts" setPending={setPending}/><ActionButton action="reject" counts={actionCounts("reject")} destructive label="Reject" setPending={setPending}/></div> : null}
    <section className="panel" aria-labelledby="manual-overview-title"><h2 id="manual-overview-title">Manual Codex-assisted Overview</h2><p>This pack does not call Codex automatically. Give the private pack to an authorized local Codex task, then import the completed draft file. Human approval remains required.</p><p>For stale or failed items, correct the completed file and retry only those candidates, or select them again to regenerate a fresh pack. Successful drafts and human edits are preserved.</p>{packs.isLoading ? <LoadingState label="Loading Overview packs…"/> : latestPack ? <><dl className="detail-grid"><Detail label="Pack ID" value={latestPack.id}/><Detail label="Version" value={latestPack.pack_version}/><Detail label="Hash" value={latestPack.pack_hash}/><Detail label="Created" value={date(latestPack.created_at)}/><Detail label="Status" value={humanize(latestPack.status)}/><Detail label="Counts" value={`${latestPack.eligible_count} eligible · ${latestPack.ineligible_count} ineligible · ${latestPack.imported_count} imported · ${latestPack.failed_count} failed`}/></dl><div className="row-actions"><button className="secondary-button" onClick={() => void downloadPack(latestPack)} type="button">Download private pack</button><label>Completed JSON response<input accept="application/json,.json" onChange={(event) => setResponseFile(event.target.files?.[0] ?? null)} type="file"/></label><button className="action-button" disabled={!responseFile || importPack.isPending} onClick={() => importPack.mutate()} type="button">Import completed file</button></div>{latestPack.items.some((item) => item.failure_code || item.exclusion_reasons.length) ? <ul className="review-issues">{latestPack.items.filter((item) => item.failure_code || item.exclusion_reasons.length).map((item) => <li key={item.candidate_id}>{item.candidate_id}: {item.failure_message ?? item.exclusion_reasons.join(" ")}</li>)}</ul> : null}</> : <p>No manual Overview pack has been prepared.</p>}</section>
    {pending ? <div aria-labelledby="bulk-confirm-title" aria-modal="true" className="confirm-dialog" role="dialog"><div><h2 id="bulk-confirm-title">Confirm {pending.label}</h2><p>{pending.processing ? `${selectedCount} selected · ${processingEligible} eligible · ${processingBlocked} ineligible · ${humanize(pending.selectionMode ?? selectionMode)} selection.` : `This action applies to ${selectedCount} selected candidate(s).`} It never publishes a Project.</p>{pending.processing && processingBlocked ? <InlineFeedback tone="error">Remove ineligible records before starting. {selectedInfo.flatMap((item) => item.processing_eligibility_errors.map((value) => `${item.project_name}: ${value}`)).join(" ")}</InlineFeedback> : null}<ul className="confirmation-list">{selectedInfo.map((item) => <li key={item.project_name}>{item.project_name}</li>)}</ul>{new Set(selectedInfo.map((item) => item.owner_developer)).size > 1 && pending.action === "assign-developer" ? <InlineFeedback tone="info">The selection contains mixed proposed Developers.</InlineFeedback> : null}{new Set(selectedInfo.map((item) => item.owner_area)).size > 1 && pending.action === "assign-area" ? <InlineFeedback tone="info">The selection contains mixed proposed Areas.</InlineFeedback> : null}{pending.action === "reject" ? <label>Required rejection reason<textarea required rows={3} value={reason} onChange={(event) => setReason(event.target.value)}/></label> : null}<div className="row-actions"><button className="secondary-button" onClick={() => setPending(null)} type="button">Cancel</button><button className={pending.destructive ? "action-button action-button--archive" : "action-button"} disabled={bulk.isPending || processing.isPending || (pending.processing && processingBlocked > 0) || (pending.action === "reject" && reason.trim().length < 3)} onClick={() => pending.processing ? processing.mutate() : bulk.mutate(pending.action)} type="button">Confirm</button></div></div></div> : null}
  </section>;
}

export function ProjectImportCandidateDetail({ batchId, candidateId }: Readonly<{ batchId: string; candidateId: string }>) {
  const query = useQuery({ queryKey: ["project-import-candidate", batchId, candidateId], queryFn: () => api<CandidateDetail>(`/admin/project-imports/${batchId}/candidates/${candidateId}`) });
  const developers = useQuery({ queryKey: ["import-developers"], queryFn: () => api<PageResponse<Option>>("/admin/developers?page_size=100") });
  const areas = useQuery({ queryKey: ["import-areas"], queryFn: () => api<PageResponse<Option>>("/admin/areas?page_size=100") });
  if (query.isLoading) return <LoadingState label="Loading candidate evidence…"/>; if (query.error) return <InlineFeedback tone="error">{query.error.message}</InlineFeedback>; if (!query.data) return null;
  return <CandidateReviewContent areas={areas.data?.items ?? []} batchId={batchId} candidateId={candidateId} developers={developers.data?.items ?? []} item={query.data} key={`${candidateId}-${query.data.review_version}`}/>;
}

function CandidateReviewContent({ areas, batchId, candidateId, developers, item }: Readonly<{ areas: Option[]; batchId: string; candidateId: string; developers: Option[]; item: CandidateDetail }>) {
  const { user } = useAuth();
  const queryClient = useQueryClient();
  const [developer, setDeveloper] = useState(item.proposed_developer_id ?? "");
  const [area, setArea] = useState(item.proposed_area_id ?? "");
  const [human, setHuman] = useState(item.human_review_completed);
  const [arabicPending, setArabicPending] = useState(item.arabic_review_required);
  const research = item.acquisition_summary.source_first_research as Record<string, unknown> | undefined;
  const [contextReviewed, setContextReviewed] = useState(Boolean(research?.context_review_completed));
  const [activeTab, setActiveTab] = useState("summary");
  const [overviewLocale, setOverviewLocale] = useState<"en" | "ar">("en");
  const invalidate = () => void queryClient.invalidateQueries({ queryKey: ["project-import-candidate", batchId, candidateId] });
  const save = useMutation({ mutationFn: () => api<CandidateDetail>(`/admin/project-imports/candidates/${candidateId}`, { method: "PUT", body: JSON.stringify({ expected_version: item.review_version, proposed_developer_id: developer || null, proposed_area_id: area || null, human_review_completed: human, arabic_review_required: arabicPending, context_review_completed: contextReviewed }) }, user?.csrf_token), onSuccess: invalidate });
  const overviewApproval = useMutation({ mutationFn: (approved: boolean) => api<CandidateDetail>(`/admin/project-imports/candidates/${candidateId}/overview-approval`, { method: "POST", body: JSON.stringify({ approved, expected_source_version: item.editorial_draft?.source_version }) }, user?.csrf_token), onSuccess: invalidate });
  const facts = item.normalized_payload ?? {};
  const missing = item.missing_fields.map(humanize);
  const blockers = item.eligibility_errors;
  const tabs = [["summary", "Summary"], ["facts", "Project Facts"], ["overview", "Overview EN/AR"], ["media", "Media"], ["sources", "Sources & Evidence"], ["changes", "Changes"]] as const;
  const developerName = optionName(developers, item.proposed_developer_id) ?? item.owner_developer;
  const areaName = optionName(areas, item.proposed_area_id) ?? item.owner_area;
  const emirate = plain(facts.emirate);
  return <section className="candidate-review-workspace">
    <AdminPageHeader back={<GuardedLink className="back-link" href={`/project-imports/${batchId}`}><ArrowLeft aria-hidden size={16}/>Back to batch</GuardedLink>} description={`${developerName} · ${emirate} · ${areaName} · Last checked ${date(item.last_verified_at)}`} eyebrow="Candidate Review" title={item.project_name} action={<div className="candidate-header-actions"><StatusBadge status={item.review_status}/><StatusBadge status={item.processing_status}/><button className="action-button" onClick={() => setActiveTab(item.editorial_draft ? "overview" : "facts")} type="button">{item.editorial_draft ? "Review Overview" : "Review facts"}</button></div>}/>
    {item.automatic_recovery_needs_review ? <InlineFeedback tone="warning">Automatic recovery could not complete this candidate. Human review is required.</InlineFeedback> : null}
    <div className="candidate-header-metrics"><span>{missing.length} missing fields</span><span>{item.conflict_count} conflicts</span><span>{item.media_count} private media items</span></div>
    <nav aria-label="Candidate review sections" className="candidate-tabs" role="tablist">{tabs.map(([value, label]) => <button aria-controls={`candidate-panel-${value}`} aria-selected={activeTab === value} key={value} onClick={() => setActiveTab(value)} role="tab" type="button">{label}</button>)}</nav>
    {save.error || overviewApproval.error ? <InlineFeedback tone="error">{save.error?.message ?? overviewApproval.error?.message}</InlineFeedback> : null}
    <div aria-live="polite" className="candidate-tab-panel" id={`candidate-panel-${activeTab}`} role="tabpanel">
      {activeTab === "summary" ? <section className="candidate-summary-grid">
        <article className="panel readiness-card"><div><span className="eyebrow">Overall readiness</span><h2>{blockers.length ? "Owner review required" : "Ready for the next review gate"}</h2></div><StatusBadge status={item.processing_status}/><p>{blockers.length ? `${blockers.length} item${blockers.length === 1 ? "" : "s"} still require attention.` : "No current candidate blocker is recorded."}</p></article>
        <article className="panel"><h2>Completed steps</h2><WorkflowList values={[item.normalized_payload ? "Normalized facts acquired" : "", item.proposed_developer_id ? "Developer mapped" : "", item.proposed_area_id ? "Area mapped" : "", item.editorial_draft ? "Bilingual Overview prepared" : "", item.media_downloaded_count ? `${item.media_downloaded_count} private media items prepared` : ""]}/></article>
        <article className="panel"><h2>Blocking steps</h2><WorkflowList empty="No blocking step is recorded." values={blockers}/></article>
        <article className="panel"><h2>Required owner actions</h2><WorkflowList values={[item.editorial_draft?.approval_status === "needs-review" ? "Review and approve or reject the bilingual Overview" : "", item.rights_status === "pending" ? "Review media rights before any future public use" : "", !contextReviewed ? "Complete the Project-specific source context review" : "", arabicPending ? "Complete the Arabic evidence review" : "", !human ? "Complete the human field review" : ""]}/></article>
        <article className="panel candidate-key-facts"><h2>Key Project facts</h2><dl className="detail-grid"><Detail label="Developer" value={developerName}/><Detail label="Emirate" value={emirate}/><Detail label="Area" value={areaName}/><Detail label="Property types" value={plain(facts.property_types)}/><Detail label="Bedrooms" value={plain(facts.bedrooms)}/><Detail label="Handover" value={`${plain(facts.handover_quarter)} ${plain(facts.handover_year)}`}/></dl></article>
        <article className="panel"><h2>Overview and media</h2><dl className="detail-grid"><Detail label="Overview" value={item.editorial_draft ? `${humanize(item.editorial_draft.approval_status)} · ${humanize(item.editorial_draft.origin ?? "api-assisted")}` : "Not prepared"}/><Detail label="Fact guard" value={item.editorial_draft?.origin === "CODEX_ASSISTED_MANUAL" ? "Passed on import" : item.overview_generation ? humanize(String(item.overview_generation.fact_guard_result.passed ? "passed" : "blocked")) : "Not run"}/><Detail label="Media rights" value={humanize(item.rights_status)}/><Detail label="Recommended next action" value={item.editorial_draft?.approval_status === "needs-review" ? "Review bilingual Overview" : "Resolve the first blocking item"}/></dl></article>
      </section> : null}
      {activeTab === "facts" ? <section className="facts-workspace">
        <FactGroup title="Identity and location" fields={[["Project name", item.owner_manifest_values.owner_project_name, facts.project_name], ["Developer", item.owner_manifest_values.owner_developer, developerName], ["Emirate", "—", facts.emirate], ["Area", item.owner_manifest_values.owner_area, areaName]]}/>
        <div className="review-mapping-actions"><label>Canonical Developer<select value={developer} onChange={(event) => setDeveloper(event.target.value)}><option value="">Unresolved</option>{developers.map((value) => <option key={value.id} value={value.id}>{recordName(value)}</option>)}</select></label><label>Canonical Area<select value={area} onChange={(event) => setArea(event.target.value)}><option value="">Unresolved</option>{areas.map((value) => <option key={value.id} value={value.id}>{recordName(value)}</option>)}</select></label></div>
        <FactGroup title="Property and unit types" fields={[["Property types", item.owner_manifest_values.owner_property_types, facts.property_types], ["Unit types", "—", facts.unit_types]]}/>
        <FactGroup title="Bedrooms and sizes" fields={[["Bedrooms", item.owner_manifest_values.owner_bedrooms, facts.bedrooms], ["Size range", "—", [facts.size_min, facts.size_max, facts.size_unit].filter(Boolean).join(" – ")]]}/>
        <FactGroup title="Payment plan" fields={[["Plan", item.owner_manifest_values.owner_payment_plan, facts.payment_plan], ["Down payment", "—", facts.down_payment_percentage], ["Milestones", "—", facts.payment_milestones]]}/>
        <FactGroup title="Handover" fields={[["Handover", item.owner_manifest_values.owner_handover, `${plain(facts.handover_quarter)} ${plain(facts.handover_year)}`]]}/>
        <FactGroup title="Availability and construction" fields={[["Availability", item.owner_manifest_values.owner_availability, facts.availability_status], ["Construction", item.owner_manifest_values.owner_construction_status, facts.construction_status]]}/>
        <FactGroup title="Amenities and nearby places" fields={[["Amenities", "—", facts.amenities], ["Nearby places", "—", facts.nearby_places]]}/>
        <FactGroup title="Floor plan and master plan" fields={[["Floor plans", "—", facts.floor_plan_units ?? facts.floor_plans], ["Master plan", "—", facts.master_plan_present]]}/>
      </section> : null}
      {activeTab === "overview" ? <section className="panel overview-review-panel"><div className="section-heading"><div><span className="eyebrow">Editorial review gate</span><h2>Overview EN/AR</h2></div><StatusBadge status={item.editorial_draft?.approval_status ?? "not-generated"}/></div>{item.overview_provider.state === "configuration-required" && !item.editorial_draft ? <InlineFeedback tone="info">{item.overview_provider.message}. Configure an approved AI provider, or prepare and import a Manual Codex Overview Pack from the batch workspace.</InlineFeedback> : null}{item.editorial_draft?.origin === "CODEX_ASSISTED_MANUAL" ? <InlineFeedback tone="info">Overview Ready for Review · Codex-assisted manual draft · Pending Human Approval. No provider or model provenance applies.</InlineFeedback> : null}<div className="locale-tabs" role="tablist"><button aria-selected={overviewLocale === "en"} onClick={() => setOverviewLocale("en")} role="tab" type="button">English</button><button aria-selected={overviewLocale === "ar"} onClick={() => setOverviewLocale("ar")} role="tab" type="button">العربية</button></div>{overviewLocale === "en" ? <article className="overview-copy"><h3>English draft</h3><p>{item.editorial_draft?.overview_en || "No editorial Overview has been generated."}</p></article> : <article className="overview-copy overview-copy--ar" dir="rtl"><h3>النص العربي</h3><p>{item.editorial_draft?.overview_ar || "لم تتم صياغة نظرة عامة تحريرية بعد."}</p></article>}<dl className="detail-grid"><Detail label="Draft method" value={item.editorial_draft?.origin === "CODEX_ASSISTED_MANUAL" ? "Codex-assisted manual" : item.editorial_draft ? "Approved API provider" : "Not generated"}/><Detail label="Fact guard" value={item.editorial_draft?.origin === "CODEX_ASSISTED_MANUAL" ? "English and Arabic passed on import" : "See generation result"}/><Detail label="Human approval" value={humanize(item.editorial_draft?.approval_status ?? "not generated")}/><Detail label="Meaning equivalence" value={item.editorial_draft ? "Requires final human confirmation" : "Not checked"}/></dl><p className="section-guidance">Approving this Overview does not create or publish a Project.</p>{item.editorial_draft?.approval_status === "needs-review" ? <div className="row-actions"><button className="action-button" disabled={overviewApproval.isPending} onClick={() => overviewApproval.mutate(true)} type="button">Approve bilingual Overview</button><button className="secondary-button" disabled={overviewApproval.isPending} onClick={() => overviewApproval.mutate(false)} type="button">Reject Overview</button></div> : null}</section> : null}
      {activeTab === "media" ? <section className="panel"><div className="section-heading"><div><span className="eyebrow">Prepared Project gallery</span><h2>Media</h2></div></div><dl aria-label="Candidate media summary" className="candidate-media-summary"><Detail label="Total acquired" value={String(item.media_summary.total_acquired)}/><Detail label="Approved" value={String(item.media_summary.approved)}/><Detail label="Removed" value={String(item.media_summary.removed)}/></dl>{item.staged_media.length ? <div className="private-media-grid private-media-grid--review">{item.staged_media.map((media) => <CandidateMediaCard key={media.id} media={media}/>)}</div> : <EmptyState description="No scraped image passed the existing validation, source and approval requirements." title="No approved media"/>}</section> : null}
      {activeTab === "sources" ? <section className="panel"><h2>Sources &amp; Evidence</h2>{item.evidence.length ? <div className="evidence-list">{item.evidence.map((value, index) => <article key={`${String(value.source_url ?? "source")}-${index}`}><div><strong>{humanize(String(value.source_type ?? "Evidence"))}</strong><span>{sourceTitle(String(value.source_url ?? ""))}</span></div><StatusBadge status={String(value.outcome ?? "recorded")}/><span>Retrieved {date(String(value.retrieved_at ?? ""))}</span>{value.source_url ? <a className="table-link" href={String(value.source_url)} rel="noreferrer" target="_blank">Open evidence source</a> : null}</article>)}</div> : <p>No source evidence is available.</p>}<details className="technical-details"><summary>Technical details</summary><dl className="detail-grid"><Detail label="Adapter" value={`${item.adapter_key ?? "—"}@${item.adapter_version ?? "—"}`}/><Detail label="Candidate version" value={String(item.review_version)}/></dl><pre>{json({ raw_source_payload: item.raw_source_payload, acquisition_summary: item.acquisition_summary })}</pre></details></section> : null}
      {activeTab === "changes" ? <section className="panel"><h2>Changes</h2>{item.changes.length ? <div className="change-list">{item.changes.map((change, index) => <article key={index}><div><strong>{humanize(String(change.field_name ?? change.classification ?? "Change"))}</strong><span>{date(String(change.detected_at ?? ""))}</span></div><dl className="detail-grid"><Detail label="Before" value={plain(change.existing_value)}/><Detail label="After" value={plain(change.new_value)}/></dl></article>)}</div> : <p>No refresh change has been recorded.</p>}</section> : null}
    </div>
    <aside className="sticky-actions candidate-sticky-actions" aria-label="Candidate review actions"><div><strong>{save.isPending ? "Saving review changes…" : "Candidate remains review-gated"}</strong><span>{blockers.length ? `${blockers.length} blocker${blockers.length === 1 ? "" : "s"} prevent readiness.` : "No current blocker is recorded."}</span></div><div className="command-actions"><label className="check"><input checked={contextReviewed} onChange={(event) => setContextReviewed(event.target.checked)} type="checkbox"/>Project source context reviewed</label><label className="check"><input checked={!arabicPending} onChange={(event) => setArabicPending(!event.target.checked)} type="checkbox"/>Arabic evidence reviewed</label><label className="check"><input checked={human} onChange={(event) => setHuman(event.target.checked)} type="checkbox"/>Human field review complete</label><button className="secondary-button" onClick={() => setActiveTab(item.editorial_draft ? "overview" : "facts")} type="button">{item.editorial_draft ? "Review Overview" : "Resolve blockers"}</button><button className="action-button" disabled={save.isPending} onClick={() => save.mutate()} type="button">Save review changes</button></div></aside>
  </section>;
}

function CandidateMediaCard({ media }: Readonly<{ media: CandidateMedia }>) {
  return <article>{media.has_thumbnail ? <PrivateThumbnail id={media.id} label={media.alt_en_draft ?? `${humanize(media.category)} for this Project`}/> : <div className="media-placeholder">Preview unavailable</div>}<div className="candidate-media-card-meta"><strong>{humanize(media.category)}</strong><span>{media.width ?? "—"} × {media.height ?? "—"}</span>{media.has_full_preview ? <a className="table-link" href={`${API_URL}/admin/project-import-media/${media.id}/preview`} rel="noreferrer" target="_blank">View</a> : null}</div></article>;
}

function PrivateThumbnail({ id, label }: Readonly<{ id: string; label: string }>) { const [url, setUrl] = useState(""); useEffect(() => { let active = true; let objectUrl = ""; void fetch(`${API_URL}/admin/project-import-media/${id}/thumbnail`, { credentials: "include", cache: "no-store" }).then((response) => { if (!response.ok) throw new Error("Preview unavailable"); return response.blob(); }).then((blob) => { objectUrl = URL.createObjectURL(blob); if (active) setUrl(objectUrl); }).catch(() => undefined); return () => { active = false; if (objectUrl) URL.revokeObjectURL(objectUrl); }; }, [id]); return url ? <Image alt={label} height={180} src={url} unoptimized width={270}/> : <div className="media-placeholder">Loading private preview…</div>; }
function ActionButton({ action, counts, destructive, disabled, label, setPending }: Readonly<{ action: string; counts: { eligible: number; blocked: number }; destructive?: boolean; disabled?: boolean; label: string; setPending: (value: PendingAction) => void }>) { return <button disabled={disabled || counts.eligible === 0 || counts.blocked > 0} onClick={() => setPending({ action, label, destructive })} title={counts.blocked ? `${counts.eligible} eligible, ${counts.blocked} blocked` : `${counts.eligible} eligible`} type="button">{label}<small>{counts.eligible} eligible{counts.blocked ? `, ${counts.blocked} blocked` : ""}</small></button>; }
function FactGroup({ title, fields }: Readonly<{ title: string; fields: ReadonlyArray<readonly [string, unknown, unknown]> }>) { return <section className="panel fact-group"><h2>{title}</h2><div className="fact-review-list">{fields.map(([label, acquired, current]) => <article key={label}><div><strong>{label}</strong><StatusBadge status={factReviewState(acquired, current)}/></div><dl><div><dt>Acquired proposal</dt><dd>{plain(acquired)}</dd></div><div><dt>Current normalized value</dt><dd>{plain(current)}</dd></div></dl></article>)}</div></section>; }
function WorkflowList({ values, empty = "No action is required." }: Readonly<{ values: string[]; empty?: string }>) { const visible = values.filter(Boolean); return visible.length ? <ul className="workflow-list">{visible.map((value) => <li key={value}>{humanize(value)}</li>)}</ul> : <p>{empty}</p>; }
function Filter({ label, value, options, onChange }: Readonly<{ label: string; value: string; options: string[]; onChange: (value: string) => void }>) { return <label>{label}<select value={value} onChange={(event) => onChange(event.target.value)}><option value="">All</option>{options.map((item) => <option key={item} value={item}>{humanize(item)}</option>)}</select></label>; }
function SelectOption({ label, value, records, onChange }: Readonly<{ label: string; value: string; records: Option[]; onChange: (value: string) => void }>) { return <label>{label}<select value={value} onChange={(event) => onChange(event.target.value)}><option value="">All</option>{records.map((item) => <option key={item.id} value={item.id}>{recordName(item)}</option>)}</select></label>; }
function Detail({ label, value }: Readonly<{ label: string; value: string }>) { return <div><dt>{label}</dt><dd>{value}</dd></div>; }
function optionName(records: Option[] | undefined, id?: string | null) { const record = id ? records?.find((item) => item.id === id) : undefined; return record ? recordName(record) : null; }
function recordName(item: Option) { return item.translations?.en?.name ?? item.name_en ?? item.slug ?? item.id; }
function date(value?: string | null) { return value ? new Date(value).toLocaleString("en-AE") : "—"; }
function plain(value: unknown) { return value === null || value === undefined || value === "" ? "—" : typeof value === "object" ? JSON.stringify(value) : String(value); }
function factReviewState(acquired: unknown, current: unknown) { if (current === null || current === undefined || current === "" || (Array.isArray(current) && current.length === 0)) return "missing"; if (acquired === null || acquired === undefined || acquired === "—") return "needs-review"; return JSON.stringify(acquired).toLocaleLowerCase() === JSON.stringify(current).toLocaleLowerCase() ? "verified" : "conflict"; }
function sourceDomain(value: string) { try { return new URL(value).hostname; } catch { return "—"; } }
function sourceTitle(value: string) { const domain = sourceDomain(value); return domain === "—" ? "Official source" : `Official source · ${domain}`; }
function humanize(value: string) { return value.replaceAll("_", " ").replaceAll("-", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function json(value: unknown) { return JSON.stringify(value, null, 2); }
