"use client";

import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, ExternalLink, SearchCheck } from "lucide-react";
import Image from "next/image";
import { useRouter } from "next/navigation";

import { API_URL, api, type PageResponse } from "../lib/api";
import { AdminPageHeader, DataTableShell, EmptyState, InlineFeedback, LoadingState, StatusBadge } from "./admin-ui";
import { useAuth } from "./auth-provider";
import { GuardedLink } from "./navigation-guard";

type ImportBatch = { id: string; name: string; source_reference: string; started_at?: string | null; completed_at?: string | null; total_count: number; clean_count: number; needs_review_count: number; failed_count: number };
type Option = { id: string; slug?: string; name_en?: string; translations?: { en?: { name?: string } } };
type Eligibility = Record<string, boolean>;
type CandidateSummary = { id: string; manifest_row_id: number; project_name: string; owner_developer: string; owner_area: string; proposed_developer_id?: string | null; proposed_area_id?: string | null; official_source_url?: string | null; review_status: string; processing_status: string; processing_eligibility_errors: string[]; missing_fields: string[]; blockers: string[]; warnings: string[]; conflict_count: number; media_count: number; media_downloaded_count: number; media_failed_count: number; last_verified_at?: string | null; review_version: number; human_review_completed: boolean; arabic_review_state: string; rights_status: string; eligibility: Eligibility };
type CandidateInfo = Pick<CandidateSummary, "project_name" | "owner_developer" | "owner_area" | "review_status" | "eligibility" | "processing_eligibility_errors">;
type BatchDetail = ImportBatch & { metrics: Record<string, number>; candidates: CandidateSummary[]; candidate_meta: { page: number; page_size: number; total: number; pages: number }; filtered_candidate_ids: string[]; filtered_candidate_versions: Record<string, number>; filtered_candidate_info: Record<string, CandidateInfo>; all_candidate_ids: string[]; all_candidate_versions: Record<string, number>; all_candidate_info: Record<string, CandidateInfo> };
type CandidateMedia = { id: string; category: string; source_url: string; rights_status: string; rights_basis?: string | null; stage_status: string; has_thumbnail: boolean; width?: number; height?: number; size_bytes?: number; duplicate_of_id?: string | null; retrieved_at?: string | null; failure_reason?: string | null; normalized_filename?: string | null; display_order: number; alt_en_draft?: string | null; alt_ar_draft?: string | null; title_en?: string | null; title_ar?: string | null; description_en?: string | null; description_ar?: string | null; tags?: string[]; derivatives: Array<Record<string, unknown>>; change_status: string };
type CandidateDetail = CandidateSummary & { batch_id: string; owner_manifest_values: Record<string, unknown>; normalized_payload: Record<string, unknown> | null; raw_source_payload: Record<string, unknown>; source_urls: string[]; arabic_review_required: boolean; acquisition_summary: Record<string, unknown>; match_result: Record<string, unknown> | null; validation_errors: unknown[]; conflict_reasons: string[]; eligibility_errors: string[]; evidence: Array<Record<string, unknown>>; staged_media: CandidateMedia[]; changes: Array<Record<string, unknown>>; human_edited_fields: string[]; editorial_draft: { overview_en?: string | null; overview_ar?: string | null; source_version: string; model_name?: string | null; model_version?: string | null; approval_status: string } | null; content_hash: string; adapter_key?: string | null; adapter_version?: string | null };
type Filters = { q: string; status: string; developer: string; area: string; areaMapping: string; source: string; missing: string; conflicts: string; media: string; arabic: string; sort: string; direction: string; page: number };
type PendingAction = { action: string; label: string; destructive?: boolean; processing?: boolean; selectionMode?: string } | null;

const initialFilters: Filters = { q: "", status: "", developer: "", area: "", areaMapping: "", source: "", missing: "", conflicts: "", media: "", arabic: "", sort: "row", direction: "asc", page: 1 };

export function ProjectImportList() {
  const query = useQuery({ queryKey: ["project-imports"], queryFn: () => api<PageResponse<ImportBatch>>("/admin/project-imports") });
  return <section><AdminPageHeader description="Review staged evidence before any candidate can become a canonical Project. This queue never publishes automatically." eyebrow="Off-Plan CMS" title="Project Imports"/>{query.isLoading ? <LoadingState label="Loading import batches…"/> : query.error ? <InlineFeedback tone="error">{query.error.message}</InlineFeedback> : !query.data?.items.length ? <DataTableShell label="Project import batches"><EmptyState description="No import batch exists. The owner manifest remains an inert intake file." title="No Project imports yet"/></DataTableShell> : <DataTableShell label="Project import batches"><table><thead><tr><th>Batch</th><th>Source</th><th>Total</th><th>Needs Review</th><th>Failed</th><th>Started</th><th>Action</th></tr></thead><tbody>{query.data.items.map((batch) => <tr key={batch.id}><td><strong>{batch.name}</strong></td><td>{batch.source_reference}</td><td>{batch.total_count}</td><td>{batch.needs_review_count}</td><td>{batch.failed_count}</td><td>{date(batch.started_at)}</td><td><GuardedLink className="table-link" href={`/project-imports/${batch.id}`}><SearchCheck aria-hidden size={15}/>Review batch</GuardedLink></td></tr>)}</tbody></table></DataTableShell>}</section>;
}

export function ProjectImportDetail({ id }: Readonly<{ id: string }>) {
  const { user } = useAuth();
  const router = useRouter();
  const queryClient = useQueryClient();
  const [filters, setFilters] = useState(initialFilters);
  const [selected, setSelected] = useState<Record<string, number>>({});
  const [pending, setPending] = useState<PendingAction>(null);
  const [developer, setDeveloper] = useState("");
  const [area, setArea] = useState("");
  const [reason, setReason] = useState("");
  const [selectionMode, setSelectionMode] = useState("manual");
  const params = useMemo(() => { const value = new URLSearchParams({ page: String(filters.page), page_size: "25", sort: filters.sort, direction: filters.direction }); if (filters.q) value.set("q", filters.q); if (filters.status) value.set("review_status", filters.status); if (filters.developer) value.set("developer_id", filters.developer); if (filters.area) value.set("area_id", filters.area); if (filters.areaMapping) value.set("area_mapping", filters.areaMapping); if (filters.source) value.set("official_source", filters.source); if (filters.missing) value.set("missing_evidence", filters.missing); if (filters.conflicts) value.set("has_conflicts", filters.conflicts); if (filters.media) value.set("media_status", filters.media); if (filters.arabic) value.set("arabic_review", filters.arabic); return value.toString(); }, [filters]);
  const query = useQuery({ queryKey: ["project-import", id, params], queryFn: () => api<BatchDetail>(`/admin/project-imports/${id}?${params}`) });
  const developers = useQuery({ queryKey: ["import-developers"], queryFn: () => api<PageResponse<Option>>("/admin/developers?page_size=100") });
  const areas = useQuery({ queryKey: ["import-areas"], queryFn: () => api<PageResponse<Option>>("/admin/areas?page_size=100") });
  const bulk = useMutation({ mutationFn: (action: string) => api<{ message: string }>(`/admin/project-imports/${id}/bulk`, { method: "POST", body: JSON.stringify({ action, candidate_ids: Object.keys(selected), expected_versions: selected, idempotency_key: crypto.randomUUID(), developer_id: action === "assign-developer" ? developer : null, area_id: action === "assign-area" ? area : null, rejection_reason: action === "reject" ? reason : null }) }, user?.csrf_token), onSuccess: () => { setSelected({}); setPending(null); setReason(""); void queryClient.invalidateQueries({ queryKey: ["project-import", id] }); } });
  const processing = useMutation({ mutationFn: () => api<{ id: string }>(`/admin/project-imports/${id}/processing-jobs`, { method: "POST", body: JSON.stringify({ requested_action: "clean-and-prepare", selection_mode: selectionMode, candidate_ids: Object.keys(selected), idempotency_key: crypto.randomUUID() }) }, user?.csrf_token), onSuccess: (job) => { setPending(null); router.push(`/project-processing/${job.id}`); } });
  const updateFilter = (key: keyof Filters, value: string | number) => setFilters((current) => ({ ...current, [key]: value, page: key === "page" ? Number(value) : 1 }));
  if (query.isLoading) return <LoadingState label="Loading import review…"/>;
  if (query.error) return <InlineFeedback tone="error">{query.error.message}</InlineFeedback>;
  if (!query.data) return null;
  const batch = query.data;
  const allPageSelected = batch.candidates.length > 0 && batch.candidates.every((item) => selected[item.id] === item.review_version);
  const selectedCount = Object.keys(selected).length;
  const selectedInfo = Object.keys(selected).map((candidateId) => batch.all_candidate_info[candidateId]).filter(Boolean);
  const selectedOutsidePage = selectedCount - batch.candidates.filter((item) => selected[item.id] === item.review_version).length;
  const actionCounts = (action: string) => ({ eligible: selectedInfo.filter((item) => item.eligibility[action]).length, blocked: selectedInfo.filter((item) => !item.eligibility[action]).length });
  const processingEligible = selectedInfo.filter((item) => item.processing_eligibility_errors.length === 0).length;
  const processingBlocked = selectedCount - processingEligible;
  return <section className="import-workspace"><AdminPageHeader back={<GuardedLink className="back-link" href="/project-imports"><ArrowLeft aria-hidden size={16}/>Back to Project Imports</GuardedLink>} description={batch.source_reference} eyebrow="Import Review Queue" title={batch.name}/>
    <div className="status-summary import-metrics" aria-label="Batch status filters">{[["all", "All"], ["needs-review", "Needs Review"], ["failed", "Failed"], ["ready-for-approval", "Ready"], ["rejected", "Rejected"], ["merged", "Draft created"]].map(([value, label]) => <button aria-pressed={(filters.status || "all") === value} key={value} onClick={() => updateFilter("status", value === "all" ? "" : value)} type="button"><strong>{batch.metrics[value] ?? 0}</strong><span>{label}</span></button>)}</div>
    <div className="panel import-filters"><label className="wide">Search candidates<input placeholder="Project, Developer, Area or row" value={filters.q} onChange={(event) => updateFilter("q", event.target.value)}/></label><Filter label="Status" value={filters.status} onChange={(value) => updateFilter("status", value)} options={["needs-review", "failed", "ready-for-approval", "rejected", "merged"]}/><SelectOption label="Developer" value={filters.developer} onChange={(value) => updateFilter("developer", value)} records={developers.data?.items ?? []}/><SelectOption label="Area" value={filters.area} onChange={(value) => updateFilter("area", value)} records={areas.data?.items ?? []}/><Filter label="Area mapping" value={filters.areaMapping} onChange={(value) => updateFilter("areaMapping", value)} options={["mapped", "unmapped"]}/><Filter label="Official source" value={filters.source} onChange={(value) => updateFilter("source", value)} options={["available", "missing"]}/><Filter label="Missing evidence" value={filters.missing} onChange={(value) => updateFilter("missing", value)} options={["true", "false"]}/><Filter label="Conflicts" value={filters.conflicts} onChange={(value) => updateFilter("conflicts", value)} options={["true", "false"]}/><Filter label="Media" value={filters.media} onChange={(value) => updateFilter("media", value)} options={["reference-only", "downloaded", "duplicate", "failed"]}/><Filter label="Arabic review" value={filters.arabic} onChange={(value) => updateFilter("arabic", value)} options={["reviewed", "review-required"]}/><Filter label="Sort" value={filters.sort} onChange={(value) => updateFilter("sort", value)} options={["row", "project", "status", "last-checked"]}/><Filter label="Direction" value={filters.direction} onChange={(value) => updateFilter("direction", value)} options={["asc", "desc"]}/><button className="secondary-button" onClick={() => { setFilters(initialFilters); setSelected({}); }} type="button">Reset filters</button></div>
    {bulk.error || processing.error ? <InlineFeedback tone="error">{bulk.error?.message ?? processing.error?.message}</InlineFeedback> : null}
    <div className="selection-controls"><label><input checked={allPageSelected} onChange={(event) => { setSelectionMode("current-page"); setSelected((current) => { const next = { ...current }; batch.candidates.forEach((item) => { if (event.target.checked) next[item.id] = item.review_version; else delete next[item.id]; }); return next; }); }} type="checkbox"/>Select this page</label><button className="table-link" onClick={() => { setSelectionMode("first-25"); setSelected(Object.fromEntries(batch.filtered_candidate_ids.slice(0, 25).map((candidateId) => [candidateId, batch.filtered_candidate_versions[candidateId]]))); }} type="button">Select first 25</button><button className="table-link" onClick={() => { setSelectionMode("first-50"); setSelected(Object.fromEntries(batch.filtered_candidate_ids.slice(0, 50).map((candidateId) => [candidateId, batch.filtered_candidate_versions[candidateId]]))); }} type="button">Select first 50</button><button className="table-link" onClick={() => { setSelectionMode("all-filtered"); setSelected(batch.filtered_candidate_versions); }} type="button">Select all {batch.candidate_meta.total} filtered</button><button className="table-link" onClick={() => { setSelectionMode("complete-batch"); setSelected(batch.all_candidate_versions); }} type="button">Select complete batch</button>{selectedCount ? <button className="table-link" onClick={() => { setSelected({}); setSelectionMode("manual"); }} type="button">Clear selection</button> : null}</div>
    {!batch.candidates.length ? <DataTableShell label="Import candidates"><EmptyState description="No candidates match these filters." title="No matching candidates"/></DataTableShell> : <DataTableShell label="Import candidates"><table className="import-review-table"><thead><tr><th><span className="sr-only">Select</span></th><th>Row</th><th>Project</th><th>Developer</th><th>Area</th><th>Source</th><th>Review</th><th>Processing</th><th>Missing</th><th>Conflicts</th><th>Media</th><th>Last checked</th><th>Action</th></tr></thead><tbody>{batch.candidates.map((item) => <tr key={item.id}><td><input aria-label={`Select manifest row ${item.manifest_row_id}`} checked={selected[item.id] === item.review_version} onChange={(event) => { setSelectionMode(selectedOutsidePage > 0 ? "cross-page" : "manual"); setSelected((current) => { const next = { ...current }; if (event.target.checked) next[item.id] = item.review_version; else delete next[item.id]; return next; }); }} type="checkbox"/></td><td>{item.manifest_row_id}</td><td><strong>{item.project_name}</strong></td><td>{optionName(developers.data?.items, item.proposed_developer_id) ?? item.owner_developer}</td><td>{optionName(areas.data?.items, item.proposed_area_id) ?? item.owner_area}</td><td>{item.official_source_url ? <a aria-label={`Open official source for ${item.project_name}`} href={item.official_source_url} rel="noreferrer" target="_blank"><ExternalLink aria-hidden size={15}/></a> : "—"}</td><td><StatusBadge status={item.review_status}/></td><td><StatusBadge status={item.processing_status}/></td><td>{item.missing_fields.length}</td><td>{item.conflict_count}</td><td>{item.media_downloaded_count}/{item.media_count}{item.media_failed_count ? ` (${item.media_failed_count} failed)` : ""}</td><td>{date(item.last_verified_at)}</td><td><GuardedLink className="table-link" href={`/project-imports/${id}/candidates/${item.id}`}>Review</GuardedLink></td></tr>)}</tbody></table></DataTableShell>}
    <div className="pagination"><button disabled={filters.page <= 1} onClick={() => updateFilter("page", filters.page - 1)} type="button">Previous</button><span>Page {batch.candidate_meta.page} of {batch.candidate_meta.pages}</span><button disabled={filters.page >= batch.candidate_meta.pages} onClick={() => updateFilter("page", filters.page + 1)} type="button">Next</button></div>
    {selectedCount ? <div className="bulk-toolbar" role="region" aria-label="Bulk actions"><strong>{selectedCount} selected{selectedOutsidePage > 0 ? ` · ${selectedOutsidePage} outside this page` : ""}</strong><button onClick={() => setPending({ action: "clean-and-prepare", label: "Clean and prepare", processing: true, selectionMode })} type="button">Clean and prepare<small>{processingEligible} eligible{processingBlocked ? `, ${processingBlocked} ineligible` : ""}</small></button><ActionButton action="retry-acquisition" counts={actionCounts("retry-acquisition")} label="Retry acquisition" setPending={setPending}/><select aria-label="Developer for selected candidates" value={developer} onChange={(event) => setDeveloper(event.target.value)}><option value="">Assign Developer…</option>{developers.data?.items.map((item) => <option key={item.id} value={item.id}>{recordName(item)}</option>)}</select><ActionButton action="assign-developer" counts={actionCounts("assign-developer")} disabled={!developer} label="Apply Developer" setPending={setPending}/><select aria-label="Area for selected candidates" value={area} onChange={(event) => setArea(event.target.value)}><option value="">Assign Area…</option>{areas.data?.items.map((item) => <option key={item.id} value={item.id}>{recordName(item)}</option>)}</select><ActionButton action="assign-area" counts={actionCounts("assign-area")} disabled={!area} label="Apply Area" setPending={setPending}/><ActionButton action="mark-ready" counts={actionCounts("mark-ready")} label="Mark Ready" setPending={setPending}/><ActionButton action="create-drafts" counts={actionCounts("create-drafts")} destructive label="Create Drafts" setPending={setPending}/><ActionButton action="reject" counts={actionCounts("reject")} destructive label="Reject" setPending={setPending}/></div> : null}
    {pending ? <div aria-labelledby="bulk-confirm-title" aria-modal="true" className="confirm-dialog" role="dialog"><div><h2 id="bulk-confirm-title">Confirm {pending.label}</h2><p>{pending.processing ? `${selectedCount} selected · ${processingEligible} eligible · ${processingBlocked} ineligible · ${humanize(pending.selectionMode ?? selectionMode)} selection.` : `This action applies to ${selectedCount} selected candidate(s).`} It never publishes a Project.</p>{pending.processing && processingBlocked ? <InlineFeedback tone="error">Remove ineligible records before starting. {selectedInfo.flatMap((item) => item.processing_eligibility_errors.map((value) => `${item.project_name}: ${value}`)).join(" ")}</InlineFeedback> : null}<ul className="confirmation-list">{selectedInfo.map((item) => <li key={item.project_name}>{item.project_name}</li>)}</ul>{new Set(selectedInfo.map((item) => item.owner_developer)).size > 1 && pending.action === "assign-developer" ? <InlineFeedback tone="info">The selection contains mixed proposed Developers.</InlineFeedback> : null}{new Set(selectedInfo.map((item) => item.owner_area)).size > 1 && pending.action === "assign-area" ? <InlineFeedback tone="info">The selection contains mixed proposed Areas.</InlineFeedback> : null}{pending.action === "reject" ? <label>Required rejection reason<textarea required rows={3} value={reason} onChange={(event) => setReason(event.target.value)}/></label> : null}<div className="row-actions"><button className="secondary-button" onClick={() => setPending(null)} type="button">Cancel</button><button className={pending.destructive ? "action-button action-button--archive" : "action-button"} disabled={bulk.isPending || processing.isPending || (pending.processing && processingBlocked > 0) || (pending.action === "reject" && reason.trim().length < 3)} onClick={() => pending.processing ? processing.mutate() : bulk.mutate(pending.action)} type="button">Confirm</button></div></div></div> : null}
  </section>;
}

export function ProjectImportCandidateDetail({ batchId, candidateId }: Readonly<{ batchId: string; candidateId: string }>) {
  const query = useQuery({ queryKey: ["project-import-candidate", batchId, candidateId], queryFn: () => api<CandidateDetail>(`/admin/project-imports/${batchId}/candidates/${candidateId}`) });
  const developers = useQuery({ queryKey: ["import-developers"], queryFn: () => api<PageResponse<Option>>("/admin/developers?page_size=100") });
  const areas = useQuery({ queryKey: ["import-areas"], queryFn: () => api<PageResponse<Option>>("/admin/areas?page_size=100") });
  if (query.isLoading) return <LoadingState label="Loading candidate evidence…"/>; if (query.error) return <InlineFeedback tone="error">{query.error.message}</InlineFeedback>; if (!query.data) return null;
  return <CandidateReviewContent areas={areas.data?.items ?? []} batchId={batchId} candidateId={candidateId} developers={developers.data?.items ?? []} item={query.data} key={`${candidateId}-${query.data.review_version}`}/>;
}

function CandidateReviewContent({ areas, batchId, candidateId, developers, item }: Readonly<{ areas: Option[]; batchId: string; candidateId: string; developers: Option[]; item: CandidateDetail }>) {
  const { user } = useAuth();
  const queryClient = useQueryClient();
  const [developer, setDeveloper] = useState(item.proposed_developer_id ?? "");
  const [area, setArea] = useState(item.proposed_area_id ?? "");
  const [human, setHuman] = useState(item.human_review_completed);
  const [arabicPending, setArabicPending] = useState(item.arabic_review_required);
  const invalidate = () => void queryClient.invalidateQueries({ queryKey: ["project-import-candidate", batchId, candidateId] });
  const save = useMutation({ mutationFn: () => api<CandidateDetail>(`/admin/project-imports/candidates/${candidateId}`, { method: "PUT", body: JSON.stringify({ expected_version: item.review_version, proposed_developer_id: developer || null, proposed_area_id: area || null, human_review_completed: human, arabic_review_required: arabicPending }) }, user?.csrf_token), onSuccess: invalidate });
  const overviewApproval = useMutation({ mutationFn: (approved: boolean) => api<CandidateDetail>(`/admin/project-imports/candidates/${candidateId}/overview-approval`, { method: "POST", body: JSON.stringify({ approved, expected_source_version: item.editorial_draft?.source_version }) }, user?.csrf_token), onSuccess: invalidate });
  return <section>
    <AdminPageHeader back={<GuardedLink className="back-link" href={`/project-imports/${batchId}`}><ArrowLeft aria-hidden size={16}/>Back to review workspace</GuardedLink>} description={`Manifest row ${item.manifest_row_id}`} eyebrow="Candidate Review" title={item.project_name} action={<StatusBadge status={item.processing_status}/>}/>
    <nav aria-label="Candidate detail sections" className="candidate-tabs"><a href="#summary">Summary</a><a href="#raw-evidence">Raw Evidence</a><a href="#normalized-facts">Normalized Facts</a><a href="#overview">Overview EN/AR</a><a href="#media">Media</a><a href="#diagnostics">Diagnostics</a><a href="#changes">Changes</a><a href="#history">History</a><a href="#public-preview">Public Preview</a></nav>
    {save.error || overviewApproval.error ? <InlineFeedback tone="error">{save.error?.message ?? overviewApproval.error?.message}</InlineFeedback> : null}
    <div className="review-detail-grid"><section className="panel" id="summary"><h2>Review summary</h2><ul className="review-issues">{item.eligibility_errors.length ? item.eligibility_errors.map((value) => <li key={value}>{value}</li>) : <li>No outstanding eligibility issue.</li>}</ul><label>Canonical Developer<select value={developer} onChange={(event) => setDeveloper(event.target.value)}><option value="">Unresolved</option>{developers.map((value) => <option key={value.id} value={value.id}>{recordName(value)}</option>)}</select></label><label>Canonical Area<select value={area} onChange={(event) => setArea(event.target.value)}><option value="">Unresolved</option>{areas.map((value) => <option key={value.id} value={value.id}>{recordName(value)}</option>)}</select></label><label className="check"><input checked={!arabicPending} onChange={(event) => setArabicPending(!event.target.checked)} type="checkbox"/>Arabic evidence reviewed by a human</label><label className="check"><input checked={human} onChange={(event) => setHuman(event.target.checked)} type="checkbox"/>Complete human field review</label><button className="action-button" disabled={save.isPending} onClick={() => save.mutate()} type="button">Save review decisions</button></section><section className="panel"><h2>Field comparison</h2><Comparison owner={item.owner_manifest_values} proposal={item.normalized_payload}/></section></div>
    <section className="panel" id="normalized-facts"><h2>Normalized Facts</h2><Comparison owner={item.owner_manifest_values} proposal={item.normalized_payload}/></section>
    <section className="panel" id="overview"><h2>Overview EN/AR</h2><div className="review-detail-grid"><div><h3>English draft</h3><p>{item.editorial_draft?.overview_en || "No editorial Overview has been generated."}</p></div><div><h3>Arabic draft</h3><p dir="rtl">{item.editorial_draft?.overview_ar || "لم تتم صياغة نظرة عامة تحريرية بعد."}</p></div></div><p>{item.editorial_draft ? `${humanize(item.editorial_draft.approval_status)} · source version ${item.editorial_draft.source_version}` : "Human approval is required before any future use."}</p>{item.editorial_draft?.approval_status === "needs-review" ? <div className="row-actions"><button className="action-button" disabled={overviewApproval.isPending} onClick={() => overviewApproval.mutate(true)} type="button">Approve bilingual Overview</button><button className="secondary-button" disabled={overviewApproval.isPending} onClick={() => overviewApproval.mutate(false)} type="button">Reject Overview</button></div> : null}</section>
    <section className="panel" id="public-preview"><h2>Public-safe Preview</h2><p>Preview contains normalized facts and approved editorial content only. Provider names, acquisition URLs, raw evidence and ARE Priority remain private.</p></section>
    <section className="panel" id="raw-evidence"><h2>Raw Evidence</h2>{item.evidence.map((value, index) => <dl className="detail-grid" key={`${String(value.source_url ?? "source")}-${index}`}><Detail label="Source title" value={sourceTitle(String(value.source_url ?? ""))}/><Detail label="Official domain" value={sourceDomain(String(value.source_url ?? ""))}/><Detail label="Direct source" value={String(value.source_url ?? "—")}/><Detail label="Type" value={humanize(String(value.source_type ?? "—"))}/><Detail label="Retrieved" value={date(String(value.retrieved_at ?? ""))}/><Detail label="Last verification" value={date(item.last_verified_at)}/></dl>)}</section>
    <section className="panel" id="media"><h2>Private Media</h2><div className="private-media-grid">{item.staged_media.map((media) => <MediaPreparationCard key={media.id} media={media} onSaved={invalidate}/>)}</div></section>
    <section className="panel" id="diagnostics"><h2>Diagnostics</h2><p>Open the dedicated Recovery Queue for full sanitized error history, retry controls and operator resolutions.</p><GuardedLink className="table-link" href="/project-recovery">Open Recovery Queue</GuardedLink></section>
    <section className="panel" id="changes"><h2>Changes</h2>{item.changes.length ? <ul className="review-issues">{item.changes.map((change, index) => <li key={index}>{humanize(String(change.classification ?? "change"))} · {date(String(change.detected_at ?? ""))}</li>)}</ul> : <p>No refresh change has been recorded.</p>}</section>
    <details className="panel technical-details" id="history"><summary>History and technical acquisition details</summary><dl className="detail-grid"><Detail label="Adapter" value={`${item.adapter_key ?? "—"}@${item.adapter_version ?? "—"}`}/><Detail label="Content hash" value={item.content_hash}/><Detail label="Source URLs" value={item.source_urls.join(", ") || "—"}/></dl><h3>Bounded raw payload</h3><pre>{json(item.raw_source_payload)}</pre><h3>Acquisition summary</h3><pre>{json(item.acquisition_summary)}</pre><h3>Raw refresh history</h3><pre>{json(item.changes)}</pre></details>
  </section>;
}

function MediaPreparationCard({ media, onSaved }: Readonly<{ media: CandidateMedia; onSaved: () => void }>) {
  const { user } = useAuth();
  const [value, setValue] = useState({ category: media.category, display_order: media.display_order, normalized_filename: media.normalized_filename ?? "", alt_en: media.alt_en_draft ?? "", alt_ar: media.alt_ar_draft ?? "", title_en: media.title_en ?? "", title_ar: media.title_ar ?? "", description_en: media.description_en ?? "", description_ar: media.description_ar ?? "", tags: (media.tags ?? []).join(", ") });
  const [rightsBasis, setRightsBasis] = useState(media.rights_basis ?? "");
  const update = (key: keyof typeof value, next: string | number) => setValue((current) => ({ ...current, [key]: next }));
  const preparation = useMutation({ mutationFn: () => api(`/admin/project-import-media/${media.id}/preparation`, { method: "PUT", body: JSON.stringify({ ...value, tags: value.tags.split(",").map((item) => item.trim()).filter(Boolean) }) }, user?.csrf_token), onSuccess: onSaved });
  const rights = useMutation({ mutationFn: (approved: boolean) => api(`/admin/project-import-media/${media.id}/rights-approval`, { method: "POST", body: JSON.stringify({ approved, rights_basis: rightsBasis }) }, user?.csrf_token), onSuccess: onSaved });
  const complete = Object.entries(value).every(([, item]) => String(item).trim()) && value.tags.split(",").some((item) => item.trim());
  return <article>{media.has_thumbnail ? <PrivateThumbnail id={media.id} label={`${media.category} private preview`}/> : <div className="media-placeholder">No private preview</div>}<label>Category<select value={value.category} onChange={(event) => update("category", event.target.value)}>{["cover", "gallery", "exterior", "interior", "amenities", "floor-plan", "master-plan", "location-map", "construction"].map((item) => <option key={item} value={item}>{humanize(item)}</option>)}</select></label><label>Order<input min="0" type="number" value={value.display_order} onChange={(event) => update("display_order", Number(event.target.value))}/></label><label>Public filename<input value={value.normalized_filename} onChange={(event) => update("normalized_filename", event.target.value)}/></label><label>English alt text<input value={value.alt_en} onChange={(event) => update("alt_en", event.target.value)}/></label><label>Arabic alt text<input dir="rtl" value={value.alt_ar} onChange={(event) => update("alt_ar", event.target.value)}/></label><label>English title<input value={value.title_en} onChange={(event) => update("title_en", event.target.value)}/></label><label>Arabic title<input dir="rtl" value={value.title_ar} onChange={(event) => update("title_ar", event.target.value)}/></label><label>English description<textarea rows={2} value={value.description_en} onChange={(event) => update("description_en", event.target.value)}/></label><label>Arabic description<textarea dir="rtl" rows={2} value={value.description_ar} onChange={(event) => update("description_ar", event.target.value)}/></label><label>Tags<input value={value.tags} onChange={(event) => update("tags", event.target.value)}/></label><button className="secondary-button" disabled={!complete || preparation.isPending} onClick={() => preparation.mutate()} type="button">Save media preparation</button><label>Rights basis<input value={rightsBasis} onChange={(event) => setRightsBasis(event.target.value)}/></label><div className="row-actions"><button className="secondary-button" disabled={rightsBasis.trim().length < 3 || rights.isPending} onClick={() => rights.mutate(true)} type="button">Approve rights</button><button className="secondary-button" disabled={rightsBasis.trim().length < 3 || rights.isPending} onClick={() => rights.mutate(false)} type="button">Reject rights</button></div><span>{media.width ?? "—"} × {media.height ?? "—"} · {fileSize(media.size_bytes)} · {media.derivatives.length} derivatives</span><span>{humanize(media.change_status)} · {humanize(media.stage_status)} · Rights {humanize(media.rights_status)}</span>{preparation.error || rights.error ? <span role="alert">{preparation.error?.message ?? rights.error?.message}</span> : null}</article>;
}

function PrivateThumbnail({ id, label }: Readonly<{ id: string; label: string }>) { const [url, setUrl] = useState(""); useEffect(() => { let active = true; let objectUrl = ""; void fetch(`${API_URL}/admin/project-import-media/${id}/thumbnail`, { credentials: "include", cache: "no-store" }).then((response) => { if (!response.ok) throw new Error("Preview unavailable"); return response.blob(); }).then((blob) => { objectUrl = URL.createObjectURL(blob); if (active) setUrl(objectUrl); }).catch(() => undefined); return () => { active = false; if (objectUrl) URL.revokeObjectURL(objectUrl); }; }, [id]); return url ? <Image alt={label} height={180} src={url} unoptimized width={270}/> : <div className="media-placeholder">Loading private preview…</div>; }
function ActionButton({ action, counts, destructive, disabled, label, setPending }: Readonly<{ action: string; counts: { eligible: number; blocked: number }; destructive?: boolean; disabled?: boolean; label: string; setPending: (value: PendingAction) => void }>) { return <button disabled={disabled || counts.eligible === 0 || counts.blocked > 0} onClick={() => setPending({ action, label, destructive })} title={counts.blocked ? `${counts.eligible} eligible, ${counts.blocked} blocked` : `${counts.eligible} eligible`} type="button">{label}<small>{counts.eligible} eligible{counts.blocked ? `, ${counts.blocked} blocked` : ""}</small></button>; }
function Comparison({ owner, proposal }: Readonly<{ owner: Record<string, unknown>; proposal: Record<string, unknown> | null }>) { const fields = [{ label: "Project name", owner: "owner_project_name", proposal: "project_name" }, { label: "Developer", owner: "owner_developer", proposal: "developer" }, { label: "Area", owner: "owner_area", proposal: "area" }, { label: "Property types", owner: "owner_property_types", proposal: "property_types" }, { label: "Bedrooms", owner: "owner_bedrooms", proposal: "bedrooms" }, { label: "Handover", owner: "owner_handover", proposal: "original_handover_value" }, { label: "Payment plan", owner: "owner_payment_plan", proposal: "payment_plan" }, { label: "Availability", owner: "owner_availability", proposal: "availability_status" }, { label: "Construction status", owner: "owner_construction_status", proposal: "construction_status" }]; return <div className="comparison-table"><div><strong>Field</strong><strong>Owner manifest</strong><strong>Official extracted evidence</strong><strong>State</strong></div>{fields.map((field) => { const ownerValue = owner[field.owner]; const proposalValue = proposal?.[field.proposal]; return <div key={field.label}><span>{field.label}</span><span>{plain(ownerValue)}</span><span>{plain(proposalValue)}</span><span>{comparisonState(ownerValue, proposalValue)}</span></div>; })}</div>; }
function Filter({ label, value, options, onChange }: Readonly<{ label: string; value: string; options: string[]; onChange: (value: string) => void }>) { return <label>{label}<select value={value} onChange={(event) => onChange(event.target.value)}><option value="">All</option>{options.map((item) => <option key={item} value={item}>{humanize(item)}</option>)}</select></label>; }
function SelectOption({ label, value, records, onChange }: Readonly<{ label: string; value: string; records: Option[]; onChange: (value: string) => void }>) { return <label>{label}<select value={value} onChange={(event) => onChange(event.target.value)}><option value="">All</option>{records.map((item) => <option key={item.id} value={item.id}>{recordName(item)}</option>)}</select></label>; }
function Detail({ label, value }: Readonly<{ label: string; value: string }>) { return <div><dt>{label}</dt><dd>{value}</dd></div>; }
function optionName(records: Option[] | undefined, id?: string | null) { const record = id ? records?.find((item) => item.id === id) : undefined; return record ? recordName(record) : null; }
function recordName(item: Option) { return item.translations?.en?.name ?? item.name_en ?? item.slug ?? item.id; }
function date(value?: string | null) { return value ? new Date(value).toLocaleString("en-AE") : "—"; }
function plain(value: unknown) { return value === null || value === undefined || value === "" ? "—" : typeof value === "object" ? JSON.stringify(value) : String(value); }
function comparisonState(owner: unknown, proposal: unknown) { if (owner == null && proposal == null) return "Missing"; if (proposal == null) return "Requires review"; if (owner == null) return "Source-grounded"; return JSON.stringify(owner).toLocaleLowerCase() === JSON.stringify(proposal).toLocaleLowerCase() ? "Match" : "Conflict"; }
function sourceDomain(value: string) { try { return new URL(value).hostname; } catch { return "—"; } }
function sourceTitle(value: string) { const domain = sourceDomain(value); return domain === "—" ? "Official source" : `Official source · ${domain}`; }
function fileSize(value?: number) { if (!value) return "—"; return value < 1024 * 1024 ? `${Math.round(value / 1024)} KB` : `${(value / 1024 / 1024).toFixed(1)} MB`; }
function humanize(value: string) { return value.replaceAll("_", " ").replaceAll("-", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function json(value: unknown) { return JSON.stringify(value, null, 2); }
