"use client";
/* eslint-disable @next/next/no-img-element -- authenticated private-media preview */

import { useState } from "react";
import { api, API_URL, type ResourceRecord } from "../lib/api";
import { FormSection, InlineFeedback } from "./admin-ui";
import { useAuth } from "./auth-provider";

type Media = { has_upload?: boolean; alt_en?: string | null; alt_ar?: string | null; provenance_url?: string; rights_status?: string; width?: number | null; height?: number | null; size_bytes?: number | null };

export function PropertyMediaPanel({ propertyId, record, onSaved }: Readonly<{ propertyId: string; record?: ResourceRecord; onSaved: (record: ResourceRecord) => void }>) {
  const { user } = useAuth(); const media = (record?.cover_media ?? null) as Media | null;
  const [altEn, setAltEn] = useState(media?.alt_en ?? ""); const [altAr, setAltAr] = useState(media?.alt_ar ?? ""); const [provenance, setProvenance] = useState(media?.provenance_url ?? ""); const [rights, setRights] = useState(media?.rights_status ?? "pending"); const [busy, setBusy] = useState(false); const [notice, setNotice] = useState("");
  const preview = media?.has_upload ? `${API_URL}/admin/properties/${propertyId}/cover` : null;
  async function upload(file: File | undefined) { if (!file) return; setBusy(true); setNotice(""); try { const body = new FormData(); body.append("image", file); const saved = await api<ResourceRecord>(`/admin/properties/${propertyId}/cover`, { method: "POST", body }, user?.csrf_token); onSaved(saved); setNotice("Cover uploaded and sanitized."); } catch (error) { setNotice(error instanceof Error ? error.message : "Upload failed."); } finally { setBusy(false); } }
  async function saveMetadata() { setBusy(true); setNotice(""); try { const saved = await api<ResourceRecord>(`/admin/properties/${propertyId}/cover`, { method: "PUT", body: JSON.stringify({ alt_en: altEn || null, alt_ar: altAr || null, provenance_url: provenance, rights_status: rights }) }, user?.csrf_token); onSaved(saved); setNotice("Media review saved."); } catch (error) { setNotice(error instanceof Error ? error.message : "Media review failed."); } finally { setBusy(false); } }
  return <FormSection id="media" title="Primary cover media" description="One cover only. Publication remains blocked until an uploaded image, provenance, bilingual alternative text and approved rights are present.">{preview ? <div className="property-cover-preview"><img alt="Property cover review preview" src={preview}/><small>{media?.width && media?.height ? `${media.width} × ${media.height}` : "Uploaded cover"}{media?.size_bytes ? ` · ${Math.round(media.size_bytes / 1024)} KB` : ""}</small></div> : <InlineFeedback tone="info">No cover is available.</InlineFeedback>}<div className="form-grid"><label className="wide">Upload JPEG, PNG or WebP (maximum 10 MB)<input accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={(event) => void upload(event.target.files?.[0])} type="file"/></label><label>English alternative text<input onChange={(event) => setAltEn(event.target.value)} value={altEn}/></label><label dir="rtl">النص البديل العربي<input onChange={(event) => setAltAr(event.target.value)} value={altAr}/></label><label className="wide">Image provenance URL<input dir="ltr" onChange={(event) => setProvenance(event.target.value)} type="url" value={provenance}/></label><label>Rights / approval<select onChange={(event) => setRights(event.target.value)} value={rights}><option value="pending">Pending owner approval</option><option value="approved">Approved</option><option value="rejected">Rejected</option></select></label></div><button className="action-button" disabled={busy || !provenance} onClick={() => void saveMetadata()} type="button">Save media review</button>{notice ? <InlineFeedback tone={notice.includes("failed") || notice.includes("could not") ? "error" : "success"}>{notice}</InlineFeedback> : null}</FormSection>;
}
