"use client";

import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Archive, ArrowDown, ArrowLeft, ArrowUp, Check, Plus, Save, Send, Trash2, XCircle } from "lucide-react";
import { useRouter } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import { type FieldErrors, useForm, useWatch } from "react-hook-form";

import { AdminPageHeader, ConfirmationDialog, ErrorSummary, FormSection, InlineFeedback, LanguageTabs, LoadingState, StatusBadge, StickyFormActions } from "./admin-ui";
import { useAuth } from "./auth-provider";
import { GuardedLink, useNavigationGuard } from "./navigation-guard";
import { PropertyMediaPanel } from "./property-media-panel";
import { api, type ResourceRecord } from "../lib/api";

type Kind = "property" | "insight" | "job";
type Locale = "en" | "ar";
type Source = { name: string; url: string };
type ArticleSection = { heading: string; paragraphs: string[] };
type ArticleBody = Record<string, unknown> & { introduction: string; sections: ArticleSection[]; checklistTitle: string; checklistIntro: string; checklist: string[] };
type Values = {
  slug: string; titleEn: string; titleAr: string; descriptionEn: string; descriptionAr: string;
  purpose: string; propertyType: string; emirate: string; community: string; developer: string; bedrooms: string; bathrooms: string; area: string; areaUnit: string; price: string; priceOnRequest: boolean; featured: boolean; provenance: string; externalUrl: string; sourceVerifiedAt: string; availabilityStatus: string;
  category: string; author: string; excerptEn: string; excerptAr: string; bodyEn: ArticleBody; bodyAr: ArticleBody; seoTitleEn: string; seoTitleAr: string; seoDescriptionEn: string; seoDescriptionAr: string; sourceLinks: Source[];
  department: string; location: string; employmentType: string; closingDate: string; responsibilitiesEn: string[]; responsibilitiesAr: string[]; requirementsEn: string[]; requirementsAr: string[]; benefitsEn: string[]; benefitsAr: string[];
};

const emptyBody = (): ArticleBody => ({ introduction: "", sections: [{ heading: "", paragraphs: [""] }], checklistTitle: "", checklistIntro: "", checklist: [""] });
const empty: Values = { slug: "", titleEn: "", titleAr: "", descriptionEn: "", descriptionAr: "", purpose: "buy", propertyType: "", emirate: "Dubai", community: "", developer: "", bedrooms: "", bathrooms: "", area: "", areaUnit: "sqft", price: "", priceOnRequest: true, featured: false, provenance: "", externalUrl: "", sourceVerifiedAt: "", availabilityStatus: "unverified", category: "guides", author: "ALIYAS Real Estate", excerptEn: "", excerptAr: "", bodyEn: emptyBody(), bodyAr: emptyBody(), seoTitleEn: "", seoTitleAr: "", seoDescriptionEn: "", seoDescriptionAr: "", sourceLinks: [{ name: "", url: "" }], department: "", location: "", employmentType: "Full-time", closingDate: "", responsibilitiesEn: [""], responsibilitiesAr: [""], requirementsEn: [""], requirementsAr: [""], benefitsEn: [""], benefitsAr: [""] };
const emirates = ["Abu Dhabi", "Ajman", "Dubai", "Fujairah", "Ras Al Khaimah", "Sharjah", "Umm Al Quwain"];
const required = "This field is required by the current data contract.";
const slugify = (value: string) => value.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
const clean = (values: string[]) => values.map((item) => item.trim()).filter(Boolean);
const nullableNumber = (value: string) => value === "" ? null : Number(value);
const complete = (values: Array<string | undefined>) => values.every((value) => Boolean(value?.trim()));
const asBody = (value: unknown): ArticleBody => {
  const source = value && typeof value === "object" ? value as Record<string, unknown> : {};
  return { ...source, introduction: String(source.introduction ?? ""), sections: Array.isArray(source.sections) && source.sections.length ? source.sections.map((section) => { const item = section as Record<string, unknown>; return { heading: String(item.heading ?? ""), paragraphs: Array.isArray(item.paragraphs) && item.paragraphs.length ? item.paragraphs.map(String) : [""] }; }) : [{ heading: "", paragraphs: [""] }], checklistTitle: String(source.checklistTitle ?? ""), checklistIntro: String(source.checklistIntro ?? ""), checklist: Array.isArray(source.checklist) && source.checklist.length ? source.checklist.map(String) : [""] };
};

function recordValues(data: ResourceRecord): Values {
  const translations = (data.translations ?? {}) as Record<string, Record<string, unknown>>; const en = translations.en ?? {}; const ar = translations.ar ?? {};
  return { ...empty, slug: String(data.slug ?? ""), titleEn: String(en.title ?? ""), titleAr: String(ar.title ?? ""), descriptionEn: String(en.description ?? ""), descriptionAr: String(ar.description ?? ""), purpose: String(data.purpose ?? "buy"), propertyType: String(data.property_type ?? ""), emirate: String(data.emirate ?? "Dubai"), community: String(data.community ?? ""), developer: String(data.developer ?? ""), bedrooms: data.bedrooms == null ? "" : String(data.bedrooms), bathrooms: data.bathrooms == null ? "" : String(data.bathrooms), area: data.area == null ? "" : String(data.area), areaUnit: String(data.area_unit ?? "sqft"), price: data.price == null ? "" : String(data.price), priceOnRequest: Boolean(data.price_on_request), featured: Boolean(data.featured), provenance: String(data.provenance_note ?? ""), externalUrl: String(data.external_reference_url ?? ""), sourceVerifiedAt: String(data.source_verified_at ?? ""), availabilityStatus: String(data.availability_status ?? "unverified"), category: String(data.category ?? "Guide"), author: String(data.author_display_name ?? ""), excerptEn: String(en.excerpt ?? ""), excerptAr: String(ar.excerpt ?? ""), bodyEn: asBody(en.body), bodyAr: asBody(ar.body), seoTitleEn: String(en.seo_title ?? ""), seoTitleAr: String(ar.seo_title ?? ""), seoDescriptionEn: String(en.seo_description ?? ""), seoDescriptionAr: String(ar.seo_description ?? ""), sourceLinks: ((data.source_links ?? []) as Source[]).length ? (data.source_links as Source[]) : [{ name: "", url: "" }], department: String(data.department ?? ""), location: String(data.location ?? ""), employmentType: String(data.employment_type ?? "Full-time"), closingDate: String(data.closing_date ?? ""), responsibilitiesEn: ((en.responsibilities ?? []) as string[]).length ? en.responsibilities as string[] : [""], responsibilitiesAr: ((ar.responsibilities ?? []) as string[]).length ? ar.responsibilities as string[] : [""], requirementsEn: ((en.requirements ?? []) as string[]).length ? en.requirements as string[] : [""], requirementsAr: ((ar.requirements ?? []) as string[]).length ? ar.requirements as string[] : [""], benefitsEn: ((en.benefits ?? []) as string[]).length ? en.benefits as string[] : [""], benefitsAr: ((ar.benefits ?? []) as string[]).length ? ar.benefits as string[] : [""] };
}

export function ResourceEditor({ kind, id }: Readonly<{ kind: Kind; id?: string }>) {
  const { user } = useAuth(); const router = useRouter(); const queryClient = useQueryClient(); const { setBlocked } = useNavigationGuard();
  const [notice, setNotice] = useState(""); const [locale, setLocale] = useState<Locale>("en"); const [slugEdited, setSlugEdited] = useState(Boolean(id)); const [pending, setPending] = useState<string | null>(null); const [confirmStatus, setConfirmStatus] = useState<string | null>(null);
  const errorRef = useRef<HTMLDivElement>(null);
  const plural = kind === "property" ? "properties" : kind === "insight" ? "insights" : "jobs"; const base = kind === "job" ? "/careers/jobs" : `/${plural}`; const endpoint = kind === "job" ? "/admin/jobs" : `/admin/${plural}`;
  const record = useQuery({ queryKey: [kind, id], queryFn: () => api<ResourceRecord>(`${endpoint}/${id}`), enabled: Boolean(id) });
  const { register, handleSubmit, reset, setError, clearErrors, setFocus, setValue, control, formState: { errors, isDirty } } = useForm<Values>({ defaultValues: empty });
  const values = useWatch({ control }) as Values; const currentStatus = String(record.data?.status ?? "draft"); const busy = pending !== null;
  useEffect(() => { if (record.data) reset(recordValues(record.data)); }, [record.data, reset]);
  useEffect(() => { setBlocked(isDirty); return () => setBlocked(false); }, [isDirty, setBlocked]);
  useEffect(() => { if (!isDirty) return; const warn = (event: BeforeUnloadEvent) => event.preventDefault(); window.addEventListener("beforeunload", warn); return () => window.removeEventListener("beforeunload", warn); }, [isDirty]);
  useEffect(() => { if (!id && !slugEdited) setValue("slug", slugify(values.titleEn ?? ""), { shouldDirty: Boolean(values.titleEn) }); }, [id, setValue, slugEdited, values.titleEn]);
  useEffect(() => { if (values.priceOnRequest && values.price) setValue("price", "", { shouldDirty: true }); }, [setValue, values.price, values.priceOnRequest]);

  const englishComplete = kind === "insight" ? complete([values.titleEn, values.excerptEn, values.bodyEn?.introduction, values.seoTitleEn, values.seoDescriptionEn]) : complete([values.titleEn, values.descriptionEn]);
  const arabicComplete = kind === "insight" ? complete([values.titleAr, values.excerptAr, values.bodyAr?.introduction, values.seoTitleAr, values.seoDescriptionAr]) : complete([values.titleAr, values.descriptionAr]);
  const requiredValues = [values.slug, values.titleEn, values.titleAr, ...(kind === "property" ? [values.descriptionEn, values.descriptionAr, values.propertyType, values.emirate, values.community, values.provenance] : kind === "insight" ? [values.excerptEn, values.excerptAr, values.author, values.category, values.bodyEn?.introduction, values.bodyAr?.introduction, values.seoTitleEn, values.seoTitleAr, values.seoDescriptionEn, values.seoDescriptionAr] : [values.descriptionEn, values.descriptionAr, values.department, values.location, values.employmentType, clean(values.responsibilitiesEn ?? []).join(""), clean(values.responsibilitiesAr ?? []).join(""), clean(values.requirementsEn ?? []).join(""), clean(values.requirementsAr ?? []).join("")])];
  const missing = requiredValues.filter((value) => !String(value ?? "").trim()).length;

  function payload(formValues: Values, status: string) {
    if (kind === "property") return { slug: formValues.slug, purpose: formValues.purpose, property_type: formValues.propertyType, emirate: formValues.emirate, community: formValues.community, developer: formValues.developer || null, bedrooms: nullableNumber(formValues.bedrooms), bathrooms: nullableNumber(formValues.bathrooms), area: nullableNumber(formValues.area), area_unit: formValues.area ? formValues.areaUnit : null, price: formValues.priceOnRequest ? null : nullableNumber(formValues.price), price_on_request: formValues.priceOnRequest, currency: "AED", featured: formValues.featured, provenance_note: formValues.provenance, external_reference_url: formValues.externalUrl || null, source_verified_at: formValues.sourceVerifiedAt || null, availability_status: formValues.availabilityStatus, status, translations: { en: { title: formValues.titleEn, description: formValues.descriptionEn }, ...(formValues.titleAr.trim() && formValues.descriptionAr.trim() ? { ar: { title: formValues.titleAr, description: formValues.descriptionAr } } : {}) } };
    if (kind === "insight") return { slug: formValues.slug, category: formValues.category, author_display_name: formValues.author, source_links: formValues.sourceLinks.filter((item) => item.name.trim() && item.url.trim()), status, translations: { en: { title: formValues.titleEn, excerpt: formValues.excerptEn, body: { title: formValues.titleEn, metaDescription: formValues.seoDescriptionEn, categoryLabel: formValues.category, ...formValues.bodyEn }, seo_title: formValues.seoTitleEn, seo_description: formValues.seoDescriptionEn }, ar: { title: formValues.titleAr, excerpt: formValues.excerptAr, body: { title: formValues.titleAr, metaDescription: formValues.seoDescriptionAr, categoryLabel: formValues.category, ...formValues.bodyAr }, seo_title: formValues.seoTitleAr, seo_description: formValues.seoDescriptionAr } } };
    return { slug: formValues.slug, department: formValues.department, location: formValues.location, employment_type: formValues.employmentType, closing_date: formValues.closingDate || null, status, translations: { en: { title: formValues.titleEn, description: formValues.descriptionEn, responsibilities: clean(formValues.responsibilitiesEn), requirements: clean(formValues.requirementsEn), benefits: clean(formValues.benefitsEn) }, ar: { title: formValues.titleAr, description: formValues.descriptionAr, responsibilities: clean(formValues.responsibilitiesAr), requirements: clean(formValues.requirementsAr), benefits: clean(formValues.benefitsAr) } } };
  }
  async function save(formValues: Values, nextStatus: string) {
    setNotice(""); clearErrors("root"); setPending(nextStatus);
    try { const saved = await api<ResourceRecord>(id ? `${endpoint}/${id}` : endpoint, { method: id ? "PUT" : "POST", body: JSON.stringify(payload(formValues, nextStatus)) }, user?.csrf_token); await Promise.all([queryClient.invalidateQueries({ queryKey: [plural] }), queryClient.invalidateQueries({ queryKey: [plural, "all-counts"] }), queryClient.invalidateQueries({ queryKey: ["dashboard"] })]); if (id) queryClient.setQueryData([kind, id], saved); reset(recordValues(saved)); setBlocked(false); setNotice(nextStatus === "published" || nextStatus === "open" ? `${label} ${kind === "job" ? "opened" : "published"} successfully.` : nextStatus === "archived" ? `${label} archived.` : nextStatus === "closed" ? "Job closed." : "Draft saved successfully."); if (!id) router.replace(`${base}/${saved.id}`); }
    catch (reason) { setError("root", { message: reason instanceof Error ? reason.message : `The ${label.toLowerCase()} could not be saved.` }); requestAnimationFrame(() => errorRef.current?.focus()); }
    finally { setPending(null); }
  }
  function invalid(fields: FieldErrors<Values>) { const names = Object.keys(fields) as Array<keyof Values>; const first = names[0]; if (String(first).endsWith("Ar")) setLocale("ar"); requestAnimationFrame(() => { errorRef.current?.focus(); if (first && !["bodyEn", "bodyAr", "sourceLinks"].includes(String(first))) setFocus(first); }); }
  const submit = (status: string) => handleSubmit((formValues) => save(formValues, status), invalid);
  const label = kind === "property" ? "Property" : kind === "insight" ? "Insight" : "Job";
  const errorEntries = Object.entries(errors).filter(([name]) => name !== "root");
  const sectionLinks = kind === "property" ? [["workflow", "Workflow"], ["content", "Content"], ["facts", "Facts"], ["commercial", "Commercial"], ["provenance", "Provenance"], ["media", "Media"], ["review", "Review"]] : kind === "insight" ? [["workflow", "Basics"], ["content", "Content"], ["sources", "Sources"], ["seo", "SEO"], ["review", "Review"]] : [["workflow", "Workflow"], ["content", "Content"], ["vacancy", "Vacancy"], ["responsibilities", "Responsibilities"], ["requirements", "Requirements"], ["benefits", "Benefits"], ["review", "Review"]];
  if (id && record.isLoading) return <LoadingState label={`Loading ${label.toLowerCase()}…`}/>;
  if (record.error) return <InlineFeedback tone="error">{record.error.message}</InlineFeedback>;
  return <section><AdminPageHeader back={<GuardedLink className="back-link" href={base}><ArrowLeft aria-hidden size={16}/>Back to {plural}</GuardedLink>} description="Complete both languages and required operational details before publication." eyebrow="Content editor" title={id ? `Edit ${label}` : `New ${label}`} action={<StatusBadge status={currentStatus}/>}/>
    <form className="editor-form" noValidate onSubmit={(event) => void submit("draft")(event)}><div className="editor-workspace"><nav className="editor-step-rail" aria-label={`${label} form sections`}>{sectionLinks.map(([anchor, text], index) => <a href={`#${anchor}`} key={anchor}><span>{index + 1}</span>{text}</a>)}</nav><div className="editor-main">
      <ErrorSummary focusRef={errorRef} message={errors.root?.message}>{errorEntries.length ? <ul>{errorEntries.map(([name, error]) => <li key={name}>{String(error?.message ?? `${name} needs attention.`)}</li>)}</ul> : null}</ErrorSummary>{notice ? <InlineFeedback tone="success"><Check aria-hidden size={16}/>{notice}</InlineFeedback> : null}
      <FormSection id="workflow" title="Identity and workflow" description="The stable slug is suggested from the English title until edited manually."><div className="form-grid"><label>English title<input {...register("titleEn", { required, minLength: 2 })}/></label><label>Stable slug<input dir="ltr" {...register("slug", { required, pattern: /^[a-z0-9]+(?:-[a-z0-9]+)*$/, onChange: () => setSlugEdited(true) })}/></label></div></FormSection>
      <FormSection id="content" title="Bilingual content" description="Arabic may remain explicitly incomplete in Draft. Both languages are mandatory before publication."><LanguageTabs active={locale} arabicComplete={arabicComplete} englishComplete={englishComplete} label={`${label} content language`} onChange={setLocale}>{kind === "insight" ? <InsightLocale locale={locale} register={register} values={values} setValue={setValue}/> : <div className="form-grid"><label>{locale === "ar" ? "العنوان" : "Title"}<input dir={locale === "ar" ? "rtl" : "ltr"} {...register(locale === "ar" ? "titleAr" : "titleEn", { required: kind === "property" && locale === "ar" ? false : required })}/></label><label className="wide">{locale === "ar" ? "الوصف" : "Description"}<textarea dir={locale === "ar" ? "rtl" : "ltr"} rows={5} {...register(locale === "ar" ? "descriptionAr" : "descriptionEn", { required: kind === "property" && locale === "ar" ? false : required, minLength: locale === "ar" && kind === "property" && !values.descriptionAr ? undefined : 10 })}/></label></div>}</LanguageTabs></FormSection>
      {kind === "property" ? <><PropertySections register={register} values={values}/>{id ? <PropertyMediaPanel onSaved={(saved) => { queryClient.setQueryData([kind, id], saved); reset(recordValues(saved)); }} propertyId={id} record={record.data}/> : null}</> : kind === "insight" ? <InsightSections register={register} values={values} setValue={setValue}/> : <JobSections locale={locale} register={register} values={values} setValue={setValue}/>}<div id="review"><StickyFormActions help={currentStatus === "published" || currentStatus === "open" ? "Saving changes updates the live record." : "Save privately or publish when complete."} state={isDirty ? "Unsaved changes" : id ? "No unsaved changes" : "Not saved yet"}><GuardedLink className="secondary-button" href={base}>Cancel</GuardedLink><button className="action-button" disabled={busy} type="submit"><Save aria-hidden size={16}/>{pending === "draft" ? "Saving…" : "Save Draft"}</button><button className="action-button action-button--publish" disabled={busy} onClick={() => void submit(kind === "job" ? "open" : "published")()} type="button"><Send aria-hidden size={16}/>{pending === "open" || pending === "published" ? "Publishing…" : kind === "job" ? "Open Job" : "Publish"}</button>{id && kind === "job" && currentStatus === "open" ? <button className="action-button" disabled={busy} onClick={() => setConfirmStatus("closed")} type="button"><XCircle aria-hidden size={16}/>Close</button> : null}{id && currentStatus !== "archived" ? <button className="action-button action-button--archive" disabled={busy} onClick={() => setConfirmStatus("archived")} type="button"><Archive aria-hidden size={16}/>Archive</button> : null}</StickyFormActions></div>
    </div><aside className="editor-context"><p className="eyebrow">Record summary</p><dl><div><dt>Status</dt><dd><StatusBadge status={currentStatus}/></dd></div><div><dt>English</dt><dd>{englishComplete ? "Complete" : "Incomplete"}</dd></div><div><dt>Arabic</dt><dd>{arabicComplete ? "Complete" : "Incomplete"}</dd></div><div><dt>Missing required</dt><dd>{missing}</dd></div><div><dt>Slug</dt><dd><code dir="ltr">{values.slug || "Not set"}</code></dd></div>{kind === "property" ? <div><dt>Featured</dt><dd>{values.featured ? "Yes" : "No"}</dd></div> : null}</dl></aside></div></form>
    <ConfirmationDialog confirmLabel={confirmStatus === "closed" ? "Close job" : `Archive ${label.toLowerCase()}`} description={confirmStatus === "closed" ? "The job will no longer accept public applications." : `The ${label.toLowerCase()} will no longer appear publicly.`} onCancel={() => setConfirmStatus(null)} onConfirm={() => { const status = confirmStatus; setConfirmStatus(null); if (status) void submit(status)(); }} open={Boolean(confirmStatus)} title={confirmStatus === "closed" ? "Close this job?" : `Archive this ${label.toLowerCase()}?`}/>
  </section>;
}

type Register = ReturnType<typeof useForm<Values>>["register"];
type SetValue = ReturnType<typeof useForm<Values>>["setValue"];
function PropertySections({ register, values }: Readonly<{ register: Register; values: Values }>) {
  return <><FormSection id="facts" title="Property facts"><div className="form-grid"><label>Purpose<select {...register("purpose", { required })}><option value="buy">Buy</option><option value="rent">Rent</option><option value="off-plan">Off-Plan</option></select></label><label>Property type<input {...register("propertyType", { required })}/></label><label>Emirate<select {...register("emirate", { required })}>{emirates.map((item) => <option key={item}>{item}</option>)}</select></label><label>Community / location<input {...register("community", { required })}/></label><label>Developer <small>Optional</small><input {...register("developer")}/></label><label>Bedrooms <small>Optional</small><input dir="ltr" min="0" type="number" {...register("bedrooms")}/></label><label>Bathrooms <small>Optional</small><input dir="ltr" min="0" type="number" {...register("bathrooms")}/></label><label>Area <small>Optional</small><input dir="ltr" min="0" step="0.01" type="number" {...register("area")}/></label><label>Area unit<select {...register("areaUnit")}><option value="sqft">sq ft</option><option value="sqm">sq m</option></select></label></div></FormSection><FormSection id="commercial" title="Commercial information"><div className="form-grid"><label>Price (AED)<input disabled={values.priceOnRequest} dir="ltr" min="0" step="0.01" type="number" {...register("price")}/><small>{values.priceOnRequest ? "Disabled because Price on request is selected." : "Required unless Price on request is selected."}</small></label><label className="check help-check"><input type="checkbox" {...register("priceOnRequest")}/><span><strong>Price on request</strong><small>Clears and disables the numeric price.</small></span></label><label className="check help-check"><input type="checkbox" {...register("featured")}/><span><strong>Featured</strong><small>Highlights the record without changing publication state.</small></span></label></div></FormSection><FormSection id="provenance" title="Provenance and availability"><div className="form-grid"><label className="wide">Source / provenance note<textarea rows={3} {...register("provenance", { required, minLength: 3 })}/></label><label className="wide">Original source URL<input dir="ltr" type="url" {...register("externalUrl")}/></label><label>Source verification date<input dir="ltr" type="date" {...register("sourceVerifiedAt")}/></label><label>Availability verification<select {...register("availabilityStatus")}><option value="unverified">Unverified</option><option value="verified-available">Verified available</option><option value="verified-unavailable">Verified unavailable</option></select></label></div></FormSection></>;
}

function InsightLocale({ locale, register, values, setValue }: Readonly<{ locale: Locale; register: Register; values: Values; setValue: SetValue }>) {
  const prefix = locale === "ar" ? "Ar" : "En"; const bodyKey = locale === "ar" ? "bodyAr" : "bodyEn"; const body = values[bodyKey];
  const updateBody = (next: ArticleBody) => setValue(bodyKey, next, { shouldDirty: true, shouldValidate: true });
  const updateSection = (index: number, next: Partial<ArticleSection>) => updateBody({ ...body, sections: body.sections.map((section, itemIndex) => itemIndex === index ? { ...section, ...next } : section) });
  return <div className="structured-editor"><div className="form-grid"><label>Title<input dir={locale === "ar" ? "rtl" : "ltr"} {...register(`title${prefix}` as "titleEn", { required })}/></label><label className="wide">Excerpt<textarea dir={locale === "ar" ? "rtl" : "ltr"} rows={3} {...register(`excerpt${prefix}` as "excerptEn", { required, minLength: 10 })}/></label><label className="wide">Introduction<textarea dir={locale === "ar" ? "rtl" : "ltr"} onChange={(event) => updateBody({ ...body, introduction: event.target.value })} rows={4} value={body.introduction}/></label></div><div className="block-list"><div className="block-list-heading"><strong>Article sections</strong><button onClick={() => updateBody({ ...body, sections: [...body.sections, { heading: "", paragraphs: [""] }] })} type="button"><Plus aria-hidden size={15}/>Add section</button></div>{body.sections.map((section, index) => <div className="content-block" key={`${bodyKey}-section-${index}`}><div className="content-block-actions"><span>Section {index + 1}</span><MoveButtons canDown={index < body.sections.length - 1} canUp={index > 0} onDown={() => updateBody({ ...body, sections: move(body.sections, index, index + 1) })} onRemove={() => updateBody({ ...body, sections: body.sections.length > 1 ? body.sections.filter((_, itemIndex) => itemIndex !== index) : body.sections })} onUp={() => updateBody({ ...body, sections: move(body.sections, index, index - 1) })}/></div><label>Heading<input dir={locale === "ar" ? "rtl" : "ltr"} onChange={(event) => updateSection(index, { heading: event.target.value })} value={section.heading}/></label><StringList label="Paragraphs" onChange={(paragraphs) => updateSection(index, { paragraphs })} values={section.paragraphs}/></div>)}</div><div className="form-grid"><label>Checklist heading<input onChange={(event) => updateBody({ ...body, checklistTitle: event.target.value })} value={body.checklistTitle}/></label><label className="wide">Checklist introduction<textarea onChange={(event) => updateBody({ ...body, checklistIntro: event.target.value })} rows={2} value={body.checklistIntro}/></label></div><StringList label="Checklist items" onChange={(checklist) => updateBody({ ...body, checklist })} values={body.checklist}/></div>;
}

function InsightSections({ register, values, setValue }: Readonly<{ register: Register; values: Values; setValue: SetValue }>) { return <><FormSection id="sources" title="Sources" description="Use approved, trustworthy source names and complete URLs."><div className="repeater">{values.sourceLinks.map((source, index) => <div className="source-row" key={`source-${index}`}><label>Source name<input onChange={(event) => setValue("sourceLinks", values.sourceLinks.map((item, itemIndex) => itemIndex === index ? { ...item, name: event.target.value } : item), { shouldDirty: true })} value={source.name}/></label><label>Source URL<input dir="ltr" onChange={(event) => setValue("sourceLinks", values.sourceLinks.map((item, itemIndex) => itemIndex === index ? { ...item, url: event.target.value } : item), { shouldDirty: true })} type="url" value={source.url}/></label><button aria-label={`Remove source ${index + 1}`} onClick={() => setValue("sourceLinks", values.sourceLinks.length > 1 ? values.sourceLinks.filter((_, itemIndex) => itemIndex !== index) : values.sourceLinks, { shouldDirty: true })} type="button"><Trash2 aria-hidden size={16}/></button></div>)}<button className="add-row-button" onClick={() => setValue("sourceLinks", [...values.sourceLinks, { name: "", url: "" }], { shouldDirty: true })} type="button"><Plus aria-hidden size={16}/>Add source</button></div></FormSection><FormSection id="seo" title="Search metadata" description="Write clear summaries for people. Character counts are guidance, not ranking guarantees."><div className="form-grid"><label>Category<select {...register("category", { required })}><option value="guides">Guides</option><option value="market-insights">Market insights</option></select></label><label>Author display name<input {...register("author", { required })}/></label><SeoFields locale="en" register={register} values={values}/><SeoFields locale="ar" register={register} values={values}/></div><div className="search-preview"><span>Search result preview</span><strong>{values.seoTitleEn || values.titleEn || "Insight title"}</strong><code dir="ltr">aliyasrealestate.ae/en/insights/{values.slug || "insight-slug"}</code><p>{values.seoDescriptionEn || "A clear description will appear here."}</p></div></FormSection></>; }
function SeoFields({ locale, register, values }: Readonly<{ locale: Locale; register: Register; values: Values }>) { const prefix = locale === "ar" ? "Ar" : "En"; const title = values[`seoTitle${prefix}` as "seoTitleEn"]; const description = values[`seoDescription${prefix}` as "seoDescriptionEn"]; return <><label dir={locale === "ar" ? "rtl" : "ltr"}>{locale === "ar" ? "عنوان SEO العربي" : "English SEO title"}<input {...register(`seoTitle${prefix}` as "seoTitleEn", { required })}/><small>{title?.length ?? 0} characters</small></label><label dir={locale === "ar" ? "rtl" : "ltr"}>{locale === "ar" ? "وصف SEO العربي" : "English SEO description"}<textarea rows={3} {...register(`seoDescription${prefix}` as "seoDescriptionEn", { required, minLength: 10 })}/><small>{description?.length ?? 0} characters</small></label></>; }

function JobSections({ locale, register, values, setValue }: Readonly<{ locale: Locale; register: Register; values: Values; setValue: SetValue }>) { const suffix = locale === "ar" ? "Ar" : "En"; return <><FormSection id="vacancy" title="Vacancy details"><div className="form-grid"><label>Department<input {...register("department", { required })}/></label><label>Location<input {...register("location", { required })}/></label><label>Employment type<select {...register("employmentType", { required })}><option>Full-time</option><option>Part-time</option><option>Contract</option><option>Temporary</option><option>Internship</option></select></label><label>Closing date <small>Optional</small><input dir="ltr" type="date" {...register("closingDate")}/></label></div></FormSection>{(["responsibilities", "requirements", "benefits"] as const).map((field) => { const key = `${field}${suffix}` as "responsibilitiesEn"; return <FormSection id={field} key={field} title={`${field.charAt(0).toUpperCase() + field.slice(1)} · ${locale === "ar" ? "Arabic" : "English"}`}><StringList label={field} onChange={(items) => setValue(key, items, { shouldDirty: true })} values={values[key]}/></FormSection>; })}</>; }

function StringList({ label, values, onChange }: Readonly<{ label: string; values: string[]; onChange: (values: string[]) => void }>) { return <div className="repeater"><span className="field-label">{label}</span>{values.map((value, index) => <div className="repeater-row" key={`${label}-${index}`}><input aria-label={`${label} ${index + 1}`} onChange={(event) => onChange(values.map((item, itemIndex) => itemIndex === index ? event.target.value : item))} value={value}/><MoveButtons canDown={index < values.length - 1} canUp={index > 0} onDown={() => onChange(move(values, index, index + 1))} onRemove={() => onChange(values.length > 1 ? values.filter((_, itemIndex) => itemIndex !== index) : values)} onUp={() => onChange(move(values, index, index - 1))}/></div>)}<button className="add-row-button" onClick={() => onChange([...values, ""])} type="button"><Plus aria-hidden size={16}/>Add item</button></div>; }
function MoveButtons({ canUp, canDown, onUp, onDown, onRemove }: Readonly<{ canUp: boolean; canDown: boolean; onUp: () => void; onDown: () => void; onRemove: () => void }>) { return <div className="move-buttons"><button aria-label="Move up" disabled={!canUp} onClick={onUp} type="button"><ArrowUp aria-hidden size={15}/></button><button aria-label="Move down" disabled={!canDown} onClick={onDown} type="button"><ArrowDown aria-hidden size={15}/></button><button aria-label="Remove item" onClick={onRemove} type="button"><Trash2 aria-hidden size={15}/></button></div>; }
function move<T>(values: T[], from: number, to: number) { const next = [...values]; const [item] = next.splice(from, 1); if (item !== undefined) next.splice(to, 0, item); return next; }
