"use client";

import { useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowLeft, Save } from "lucide-react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";

import { useAuth } from "./auth-provider";
import { api, type ResourceRecord } from "../lib/api";

type Kind = "property" | "insight" | "job";
type Values = Record<string, string | boolean>;
const schema = z.object({
  slug: z.string().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, "Use a lowercase hyphenated slug."),
  titleEn: z.string().min(2), titleAr: z.string().min(2), descriptionEn: z.string().min(10), descriptionAr: z.string().min(10), status: z.string().min(1),
}).passthrough();

const empty: Values = { slug: "", titleEn: "", titleAr: "", descriptionEn: "", descriptionAr: "", status: "draft", purpose: "buy", propertyType: "", emirate: "", community: "", developer: "", bedrooms: "", bathrooms: "", area: "", areaUnit: "sqft", price: "", priceOnRequest: true, featured: false, provenance: "", externalUrl: "", category: "", author: "", excerptEn: "", excerptAr: "", bodyEn: "", bodyAr: "", seoTitleEn: "", seoTitleAr: "", seoDescriptionEn: "", seoDescriptionAr: "", sourceLinks: "", department: "", location: "", employmentType: "", closingDate: "", responsibilitiesEn: "", responsibilitiesAr: "", requirementsEn: "", requirementsAr: "", benefitsEn: "", benefitsAr: "" };

function nullableNumber(value: unknown) { return value === "" ? null : Number(value); }
function lines(value: unknown) { return String(value ?? "").split("\n").map((item) => item.trim()).filter(Boolean); }

export function ResourceEditor({ kind, id }: Readonly<{ kind: Kind; id?: string }>) {
  const { user } = useAuth(); const router = useRouter(); const queryClient = useQueryClient(); const [notice, setNotice] = useState("");
  const plural = kind === "property" ? "properties" : kind === "insight" ? "insights" : "jobs";
  const base = kind === "job" ? "/careers/jobs" : `/${plural}`; const endpoint = kind === "job" ? "/admin/jobs" : `/admin/${plural}`;
  const record = useQuery({ queryKey: [kind, id], queryFn: () => api<ResourceRecord>(`${endpoint}/${id}`), enabled: Boolean(id) });
  const { register, handleSubmit, reset, setError, formState: { errors, isSubmitting } } = useForm<Values>({ defaultValues: empty });
  useEffect(() => {
    if (!record.data) return;
    const data = record.data; const translations = data.translations as Record<string, Record<string, unknown>>;
    reset({ ...empty, slug: String(data.slug ?? ""), status: String(data.status ?? "draft"), titleEn: String(translations.en?.title ?? ""), titleAr: String(translations.ar?.title ?? ""), descriptionEn: String(translations.en?.description ?? ""), descriptionAr: String(translations.ar?.description ?? ""), purpose: String(data.purpose ?? "buy"), propertyType: String(data.property_type ?? ""), emirate: String(data.emirate ?? ""), community: String(data.community ?? ""), developer: String(data.developer ?? ""), bedrooms: data.bedrooms == null ? "" : String(data.bedrooms), bathrooms: data.bathrooms == null ? "" : String(data.bathrooms), area: data.area == null ? "" : String(data.area), areaUnit: String(data.area_unit ?? "sqft"), price: data.price == null ? "" : String(data.price), priceOnRequest: Boolean(data.price_on_request), featured: Boolean(data.featured), provenance: String(data.provenance_note ?? ""), externalUrl: String(data.external_reference_url ?? ""), category: String(data.category ?? ""), author: String(data.author_display_name ?? ""), excerptEn: String(translations.en?.excerpt ?? ""), excerptAr: String(translations.ar?.excerpt ?? ""), bodyEn: JSON.stringify(translations.en?.body ?? {}, null, 2), bodyAr: JSON.stringify(translations.ar?.body ?? {}, null, 2), seoTitleEn: String(translations.en?.seo_title ?? ""), seoTitleAr: String(translations.ar?.seo_title ?? ""), seoDescriptionEn: String(translations.en?.seo_description ?? ""), seoDescriptionAr: String(translations.ar?.seo_description ?? ""), sourceLinks: ((data.source_links ?? []) as {name:string;url:string}[]).map((item) => `${item.name}|${item.url}`).join("\n"), department: String(data.department ?? ""), location: String(data.location ?? ""), employmentType: String(data.employment_type ?? ""), closingDate: String(data.closing_date ?? ""), responsibilitiesEn: ((translations.en?.responsibilities ?? []) as string[]).join("\n"), responsibilitiesAr: ((translations.ar?.responsibilities ?? []) as string[]).join("\n"), requirementsEn: ((translations.en?.requirements ?? []) as string[]).join("\n"), requirementsAr: ((translations.ar?.requirements ?? []) as string[]).join("\n"), benefitsEn: ((translations.en?.benefits ?? []) as string[]).join("\n"), benefitsAr: ((translations.ar?.benefits ?? []) as string[]).join("\n") });
  }, [record.data, reset]);
  async function save(values: Values) {
    setNotice(""); const valid = schema.safeParse(values); if (!valid.success) { setError("root", { message: valid.error.issues[0]?.message ?? "Review required fields." }); return; }
    let payload: Record<string, unknown>;
    try {
      if (kind === "property") payload = { slug: values.slug, purpose: values.purpose, property_type: values.propertyType, emirate: values.emirate, community: values.community, developer: values.developer || null, bedrooms: nullableNumber(values.bedrooms), bathrooms: nullableNumber(values.bathrooms), area: nullableNumber(values.area), area_unit: values.area ? values.areaUnit : null, price: values.priceOnRequest ? null : nullableNumber(values.price), price_on_request: Boolean(values.priceOnRequest), currency: "AED", featured: Boolean(values.featured), provenance_note: values.provenance, external_reference_url: values.externalUrl || null, status: values.status, translations: { en: { title: values.titleEn, description: values.descriptionEn }, ar: { title: values.titleAr, description: values.descriptionAr } } };
      else if (kind === "insight") payload = { slug: values.slug, category: values.category, author_display_name: values.author, source_links: lines(values.sourceLinks).map((line) => { const [name, url] = line.split("|"); return { name, url }; }), status: values.status, translations: { en: { title: values.titleEn, excerpt: values.excerptEn, body: JSON.parse(String(values.bodyEn)), seo_title: values.seoTitleEn, seo_description: values.seoDescriptionEn }, ar: { title: values.titleAr, excerpt: values.excerptAr, body: JSON.parse(String(values.bodyAr)), seo_title: values.seoTitleAr, seo_description: values.seoDescriptionAr } } };
      else payload = { slug: values.slug, department: values.department, location: values.location, employment_type: values.employmentType, closing_date: values.closingDate || null, status: values.status, translations: { en: { title: values.titleEn, description: values.descriptionEn, responsibilities: lines(values.responsibilitiesEn), requirements: lines(values.requirementsEn), benefits: lines(values.benefitsEn) }, ar: { title: values.titleAr, description: values.descriptionAr, responsibilities: lines(values.responsibilitiesAr), requirements: lines(values.requirementsAr), benefits: lines(values.benefitsAr) } } };
    } catch { setError("root", { message: "Body fields must contain valid JSON." }); return; }
    try { const saved = await api<ResourceRecord>(id ? `${endpoint}/${id}` : endpoint, { method: id ? "PUT" : "POST", body: JSON.stringify(payload) }, user?.csrf_token); await queryClient.invalidateQueries({ queryKey: [plural] }); setNotice("Saved successfully."); if (!id) router.replace(`${base}/${saved.id}`); }
    catch (reason) { setError("root", { message: reason instanceof Error ? reason.message : "Save failed." }); }
  }
  if (id && record.isLoading) return <div className="panel-state">Loading record…</div>;
  if (record.error) return <div className="panel-state form-error">{record.error.message}</div>;
  const label = kind === "property" ? "Property" : kind === "insight" ? "Insight" : "Career job";
  return <section><div className="page-heading"><div><Link className="back-link" href={base}><ArrowLeft aria-hidden size={16}/>Back to {plural}</Link><h1>{id ? `Edit ${label}` : `New ${label}`}</h1><p>Bilingual fields are required before publication.</p></div></div><form className="editor-form" onSubmit={handleSubmit(save)}>
    {errors.root?.message ? <div className="form-error" role="alert">{errors.root.message}</div> : null}{notice ? <div className="form-success" role="status">{notice}</div> : null}
    <fieldset><legend>Workflow</legend><div className="form-grid"><label>Stable slug<input {...register("slug")} required/></label><label>Status<select {...register("status")}>{(kind === "job" ? ["draft","open","closed","archived"] : ["draft","published","archived"]).map((item) => <option key={item}>{item}</option>)}</select></label></div></fieldset>
    <fieldset><legend>English and Arabic content</legend><div className="form-grid"><label>English title<input {...register("titleEn")} required/></label><label dir="rtl">العنوان العربي<input {...register("titleAr")} required/></label><label>English description<textarea rows={6} {...register("descriptionEn")} required/></label><label dir="rtl">الوصف العربي<textarea rows={6} {...register("descriptionAr")} required/></label></div></fieldset>
    {kind === "property" ? <PropertyFields register={register}/> : kind === "insight" ? <InsightFields register={register}/> : <JobFields register={register}/>}<div className="form-actions"><button className="primary-button" disabled={isSubmitting} type="submit"><Save aria-hidden size={17}/>{isSubmitting ? "Saving…" : "Save record"}</button></div>
  </form></section>;
}

type Register = ReturnType<typeof useForm<Values>>["register"];
function PropertyFields({ register }: { register: Register }) { return <fieldset><legend>Property facts</legend><div className="form-grid"><label>Purpose<select {...register("purpose")}><option value="buy">Buy</option><option value="rent">Rent</option><option value="off-plan">Off-Plan</option></select></label><label>Property type<input {...register("propertyType")} required/></label><label>Emirate<input {...register("emirate")} required/></label><label>Community / location<input {...register("community")} required/></label><label>Developer<input {...register("developer")}/></label><label>Bedrooms<input min="0" type="number" {...register("bedrooms")}/></label><label>Bathrooms<input min="0" type="number" {...register("bathrooms")}/></label><label>Area<input min="0" step="0.01" type="number" {...register("area")}/></label><label>Area unit<select {...register("areaUnit")}><option value="sqft">sq ft</option><option value="sqm">sq m</option></select></label><label>Price (AED)<input min="0" step="0.01" type="number" {...register("price")}/></label><label className="check"><input type="checkbox" {...register("priceOnRequest")}/>Price on request</label><label className="check"><input type="checkbox" {...register("featured")}/>Featured</label><label className="wide">Source / provenance note<textarea rows={3} {...register("provenance")} required/></label><label className="wide">Approved external reference URL<input type="url" {...register("externalUrl")}/></label></div></fieldset>; }
function InsightFields({ register }: { register: Register }) { return <><fieldset><legend>Editorial details</legend><div className="form-grid"><label>Category<input {...register("category")} required/></label><label>Author display name<input {...register("author")} required/></label><label>English excerpt<textarea rows={3} {...register("excerptEn")} required/></label><label dir="rtl">المقتطف العربي<textarea rows={3} {...register("excerptAr")} required/></label><label>English body JSON<textarea rows={10} {...register("bodyEn")} required/></label><label dir="rtl">محتوى عربي JSON<textarea rows={10} {...register("bodyAr")} required/></label><label className="wide">Source links (one Name|URL per line)<textarea rows={4} {...register("sourceLinks")}/></label></div></fieldset><fieldset><legend>Search metadata</legend><div className="form-grid"><label>English SEO title<input {...register("seoTitleEn")} required/></label><label dir="rtl">عنوان SEO العربي<input {...register("seoTitleAr")} required/></label><label>English SEO description<textarea rows={3} {...register("seoDescriptionEn")} required/></label><label dir="rtl">وصف SEO العربي<textarea rows={3} {...register("seoDescriptionAr")} required/></label></div></fieldset></>; }
function JobFields({ register }: { register: Register }) { return <fieldset><legend>Vacancy details</legend><div className="form-grid"><label>Department<input {...register("department")} required/></label><label>Location<input {...register("location")} required/></label><label>Employment type<input {...register("employmentType")} required/></label><label>Closing date<input type="date" {...register("closingDate")}/></label><label>English responsibilities (one per line)<textarea rows={5} {...register("responsibilitiesEn")} required/></label><label dir="rtl">المسؤوليات (واحدة في كل سطر)<textarea rows={5} {...register("responsibilitiesAr")} required/></label><label>English requirements (one per line)<textarea rows={5} {...register("requirementsEn")} required/></label><label dir="rtl">المتطلبات (واحد في كل سطر)<textarea rows={5} {...register("requirementsAr")} required/></label><label>English benefits<textarea rows={4} {...register("benefitsEn")}/></label><label dir="rtl">المزايا العربية<textarea rows={4} {...register("benefitsAr")}/></label></div></fieldset>; }
