import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";

import { Breadcrumbs, FinalCta } from "../../../../../components/content/editorial-content";
import { SiteFooter } from "../../../../../components/navigation/site-footer";
import { getProperty } from "../../../../../lib/api";
import { homeCopy, isLocale } from "../../../../../lib/home-copy";
import { richCopy } from "../../../../../lib/rich-copy";
import { localizedBrand, localizedDisplayText, normalizeArabicUserFacingText } from "../../../../../lib/arabic-localization";

type Props={params:Promise<{locale:string;slug:string}>};
export const dynamic="force-dynamic";
export async function generateMetadata({params}:Props):Promise<Metadata>{const {locale,slug}=await params;if(!isLocale(locale))notFound();const property=await getProperty(locale,slug);if(!property)return {};const title=localizedDisplayText(property.title,locale);const description=locale==="ar"?normalizeArabicUserFacingText(property.description):property.description;return {title:`${title} | ${localizedBrand(locale)}`,description:description.slice(0,155)};}
export default async function PropertyDetail({params}:Props){const {locale,slug}=await params;if(!isLocale(locale))notFound();const property=await getProperty(locale,slug);if(!property)notFound();const ar=locale==="ar";const text=(value:string|number)=>ar?normalizeArabicUserFacingText(String(value)):String(value);return <div className="property-detail-page" id="top"><main id="main-content"><section className="inner-hero"><div className="inner-hero__grid"><div className="inner-hero__copy"><Breadcrumbs items={[{href:`/${locale}`,label:richCopy[locale].homeLabel},{href:`/${locale}/properties`,label:homeCopy[locale].header.properties},{label:text(property.title)}]} label={richCopy[locale].breadcrumb}/><p>{text(property.emirate)} / {text(property.property_type)}</p><h1>{text(property.title)}</h1><span>{text(property.description)}</span></div><div className="property-detail-neutral" aria-label={ar?"لا توجد وسائط معتمدة لهذا العقار":"No approved media is available for this property"}><strong>{ar?"علياس":"ARE"}</strong><span>{ar?"عرض بدون صورة":"Media-neutral presentation"}</span></div></div></section><section className="content-section content-section--split"><div className="content-heading"><p>{ar?"علياس العقارية / الحقائق":"ARE / FACTS"}</p><h2>{ar?"تفاصيل العقار المنشورة":"Published property details"}</h2><span>{ar?"تعرض هذه الصفحة فقط المعلومات المعتمدة في نظام الإدارة.":"This page shows only information approved in the Admin CMS."}</span></div><dl className="property-facts">{[[ar?"الغرض":"Purpose",property.purpose],[ar?"الموقع":"Location",`${property.community}, ${property.emirate}`],[ar?"المطور":"Developer",property.developer],[ar?"غرف النوم":"Bedrooms",property.bedrooms],[ar?"الحمامات":"Bathrooms",property.bathrooms],[ar?"المساحة":"Area",property.area?`${property.area} ${property.area_unit}`:null],[ar?"السعر":"Price",property.price_on_request?(ar?"السعر عند الطلب":"Price on request"):`${property.currency} ${property.price}`]].filter(([,value])=>value!=null).map(([label,value])=><div key={String(label)}><dt>{label}</dt><dd>{text(value as string|number)}</dd></div>)}</dl></section><Link className="article-back" href={`/${locale}/properties`}>← {ar?"العودة إلى العقارات":"Back to properties"}</Link><FinalCta action={ar?"استفسر":"Enquire"} heading={ar?"هل يناسب هذا العقار موجزك؟":"Does this property fit your brief?"} href={`/${locale}/contact`} locale={locale} text={ar?"تحقق من التوفر والتفاصيل الحالية قبل اتخاذ أي قرار.":"Verify current availability and details before making a decision."}/></main><SiteFooter copy={homeCopy[locale].header} locale={locale}/></div>}
