import type { Metadata } from "next";
import { notFound } from "next/navigation";

import { FaqSection, FinalCta, ProcessList, RelatedPages } from "../../../../components/content/editorial-content";
import { DeveloperDirectory } from "../../../../components/developers/developer-directory";
import { PageHero } from "../../../../components/hero/page-hero";
import { SiteFooter } from "../../../../components/navigation/site-footer";
import { getDevelopers } from "../../../../lib/api";
import { homeCopy, isLocale, locales, type Locale } from "../../../../lib/home-copy";
import { localizedDisplayText } from "../../../../lib/arabic-localization";

type Props = Readonly<{ params: Promise<{ locale: string }> }>;
export const dynamicParams = false;
export function generateStaticParams() { return locales.map((locale) => ({ locale })); }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { locale } = await params; if (!isLocale(locale)) notFound(); return locale === "ar" ? { title: "المطورون | علياس العقارية", description: "دليل أولي موثق المصادر لمطورين عقاريين في دبي وأبوظبي ورأس الخيمة." } : { title: "UAE Developers | ALIYAS Real Estate", description: "A source-aware starting directory of selected property developers in Dubai, Abu Dhabi and Ras Al Khaimah." }; }
export default async function DevelopersPage({ params }: Props) { const { locale } = await params; if (!isLocale(locale)) notFound(); return <LocalizedDevelopers locale={locale} />; }

async function LocalizedDevelopers({ locale }: Readonly<{ locale: Locale }>) {
  const ar = locale === "ar";
  const copy = ar ? {
    eyebrow: "دليل المطورين", title: "ابدأ بالمصدر، ثم تحقق من الفرصة الحالية.", intro: "دليل أولي لمطورين مختارين في دبي وأبوظبي ورأس الخيمة، مبني على مراجع حكومية ومواقع رسمية تمت مراجعتها في التاريخ الظاهر على كل بطاقة.", assistance: "تساعد علياس العقارية العملاء في الاستفسارات المتعلقة بالحجوزات الجديدة وفرص البيع الأولي وإعادة البيع ضمن مشاريع المطورين المدرجين في الإمارات، رهناً بالتوفر الحالي وأهلية المعاملة والتحقق.", directory: "دليل موثق المصادر", directoryTitle: "ابحث حسب الاسم أو المشروع أو الإمارة", journey: "مسار عملي", journeyTitle: "من اسم المطور إلى استفسار أوضح", disclaimer: "حدود الدليل", disclaimerTitle: "الإدراج ليس توصية أو ضماناً", disclaimerText: "يعكس هذا الدليل مراجعة أولية للمصادر الظاهرة فقط. لا يؤكد الترخيص الحالي لكل نشاط أو المشروع أو السعر أو المخزون أو التوفر أو الجودة أو العائد أو أهلية المعاملة. تحقق من السجل والوثائق والموقع الرسمي المناسب عند وقت الاستفسار، واطلب مشورة مؤهلة عند الحاجة.", faqTitle: "أسئلة عن دليل المطورين", relatedTitle: "واصل البحث", ctaTitle: "هل لديك مطور أو مشروع محدد؟", ctaText: "أرسل استفساراً منظماً وسنبدأ بالتحقق من السياق الحالي.", ctaAction: "جهّز استفسارك",
  } : {
    eyebrow: "Developer directory", title: "Start with the source, then verify the current opportunity.", intro: "A starting directory of selected developers across Dubai, Abu Dhabi and Ras Al Khaimah, based on government references and official sites reviewed on the date shown on each card.", assistance: "ALIYAS Real Estate assists clients with enquiries for new bookings, primary-sale and resale opportunities across listed UAE developer projects, subject to current availability, transaction eligibility and verification.", directory: "Source-aware directory", directoryTitle: "Search by name, project or emirate", journey: "A practical route", journeyTitle: "From developer name to a clearer enquiry", disclaimer: "Directory limits", disclaimerTitle: "Inclusion is not a recommendation or guarantee", disclaimerText: "This directory reflects an initial review of the sources shown only. It does not confirm current licensing for every activity, project, price, inventory, availability, quality, return or transaction eligibility. Recheck the appropriate register, documents and official site at enquiry time, and obtain qualified advice where needed.", faqTitle: "Developer directory questions", relatedTitle: "Continue researching", ctaTitle: "Have a developer or project in mind?", ctaText: "Send a structured enquiry and begin with current-context verification.", ctaAction: "Prepare your enquiry",
  };
  const records = await getDevelopers(locale);
  const sorted = [...(records ?? [])].sort((a, b) => a.name.localeCompare(b.name, locale));
  return <div className="developers-page" id="top"><main id="main-content">
    <PageHero description={copy.intro} eyebrow={copy.eyebrow} image="developers" locale={locale} title={copy.title}
      primary={{ label: copy.directory, href: "#developer-directory-title" }} secondary={{ label: copy.ctaAction, href: `/${locale}/contact` }}
      note={<><strong>{ar ? "علياس العقارية / المساعدة" : "ARE / ASSISTANCE"}</strong><p>{copy.assistance}</p><small>{localizedDisplayText(String(sorted.length).padStart(2, "0"), locale)} / {ar ? "مرجعاً أولياً" : "STARTING REFERENCES"}</small></>} />
    <section aria-labelledby="developer-directory-title" className="content-section developer-directory-section"><div className="content-heading"><p>{copy.directory}</p><h2 id="developer-directory-title">{copy.directoryTitle}</h2></div><DeveloperDirectory developers={sorted} locale={locale} unavailable={records === null} /></section>
    <section className="content-section content-section--dark"><div className="content-heading"><p>{copy.journey}</p><h2>{copy.journeyTitle}</h2></div><ProcessList items={ar ? [{ title: "حدّد", text: "اختر الاسم أو المشروع الذي تريد فهمه." }, { title: "تحقق", text: "راجع التسجيل والمصدر الرسمي والمعلومات الحالية." }, { title: "قارن", text: "وازن المستندات والملاءمة والتوقيت والالتزام." }, { title: "استفسر", text: "شارك أسئلتك من دون افتراض التوفر أو النتيجة." }] : [{ title: "Identify", text: "Choose the name or project you want to understand." }, { title: "Verify", text: "Review registration, the official source and current information." }, { title: "Compare", text: "Consider documents, suitability, timing and commitment." }, { title: "Enquire", text: "Share questions without assuming availability or outcome." }]} /></section>
    <section className="content-section content-section--split"><div className="content-heading"><p>{copy.disclaimer}</p><h2>{copy.disclaimerTitle}</h2></div><p className="content-lead">{copy.disclaimerText}</p></section>
    <FaqSection eyebrow="ARE / FAQ" heading={copy.faqTitle} items={ar ? [{ question: "هل يشمل الدليل كل مطوري الإمارات؟", answer: "لا. إنها مجموعة أولية مختارة من الأسماء التي راجعنا لها مصادر مناسبة لهذه المعاينة." }, { question: "هل يعني الإدراج أن المطور أو المشروع موصى به؟", answer: "لا. الإدراج مرجع بحثي وليس تصنيفاً أو توصية أو ضماناً." }, { question: "هل المشاريع المذكورة متاحة الآن؟", answer: "لا نفترض ذلك. يلزم تحقق حديث من المخزون والحالة والأهلية والأسعار." }, { question: "لماذا تظهر أسماء المطورين بالإنجليزية؟", answer: "نحافظ على الاسم الرسمي أو التجاري للتعريف الدقيق، مع شرح عربي وسياق ثنائي اللغة." }, { question: "ماذا يحدث عند الضغط على الاستفسار؟", answer: "يفتح نموذج المعاينة مع تحديد المطور ونوع الاستفسار؛ ولا يرسل النموذج بيانات في هذه المرحلة." }] : [{ question: "Does this include every UAE developer?", answer: "No. It is a selected starting set for which suitable sources were reviewed for this preview." }, { question: "Does inclusion recommend a developer or project?", answer: "No. Inclusion is a research reference, not a ranking, recommendation or guarantee." }, { question: "Are the named projects currently available?", answer: "Do not assume so. Inventory, status, eligibility and pricing need fresh verification." }, { question: "Why preserve official developer names?", answer: "Official or trading names support accurate identification, while bilingual descriptions provide context." }, { question: "What happens when I select enquire?", answer: "The preview form opens with the developer and enquiry type selected; it does not send data at this stage." }]} />
    <RelatedPages heading={copy.relatedTitle} items={ar ? [{ href: "/ar/off-plan", label: "على المخطط", text: "راجع خطوات بحث عامة." }, { href: "/ar/properties", label: "العقارات", text: "حدّد احتياجاتك العقارية." }, { href: "/ar/contact", label: "تواصل", text: "جهّز استفساراً خاصاً بمطور." }] : [{ href: "/en/off-plan", label: "Off-plan", text: "Review a careful general pathway." }, { href: "/en/properties", label: "Properties", text: "Define your property requirement." }, { href: "/en/contact", label: "Contact", text: "Prepare a developer-specific enquiry." }]} />
    <FinalCta action={copy.ctaAction} heading={copy.ctaTitle} href={`/${locale}/contact`} locale={locale} text={copy.ctaText} />
  </main><SiteFooter copy={homeCopy[locale].header} locale={locale} /></div>;
}
