import type { FaqItem, RelatedItem } from "../components/content/editorial-content";
import type { Locale } from "./home-copy";

export type InsightCategory = "guides" | "market-insights";
type LocalizedArticle = Readonly<{ title:string;metaDescription:string;categoryLabel:string;introduction:string;sections:ReadonlyArray<Readonly<{heading:string;paragraphs:ReadonlyArray<string>}>>;checklistTitle:string;checklistIntro:string;checklist:ReadonlyArray<string>;considerationsTitle:string;considerations:ReadonlyArray<Readonly<{title:string;text:string}>>;limitationsTitle:string;limitations:string;faqTitle:string;faq:ReadonlyArray<FaqItem>;relatedTitle:string;related:ReadonlyArray<RelatedItem>;sourcesTitle:string }>;
export type InsightArticle = Readonly<{ slug:string;category:InsightCategory;published:string;updated:string;sources:ReadonlyArray<Readonly<{name:string;url:string}>>;content:Readonly<Record<Locale,LocalizedArticle>> }>;
export type VerifiedUpdate = Readonly<{ id:string;sourceName:string;sourceUrl:string;published:string;verified:string;title:Readonly<Record<Locale,string>>;summary:Readonly<Record<Locale,string>> }>;

export const verifiedUpdates:ReadonlyArray<VerifiedUpdate>=[
  {id:"dld-ips-2026",sourceName:"Dubai Land Department",sourceUrl:"https://dubailand.gov.ae/en/news-media/in-partnership-with-dubai-land-department-dubai-to-host-the-22nd-edition-of-ips-2026-next-september/",published:"2026-08-03",verified:"2026-08-24",title:{en:"Dubai Land Department confirms IPS 2026 dates",ar:"دائرة الأراضي والأملاك في دبي تؤكد مواعيد معرض آي بي إس ٢٠٢٦"},summary:{en:"The official announcement confirms that the 22nd IPS edition is scheduled for 7–9 September 2026 at Dubai World Trade Centre. Event details should be checked at the source before planning attendance.",ar:"يؤكد الإعلان الرسمي إقامة الدورة الثانية والعشرين من المعرض بين ٧ و٩ سبتمبر ٢٠٢٦ في مركز دبي التجاري العالمي. ينبغي مراجعة المصدر قبل التخطيط للحضور."}},
  {id:"adrec-h1-2026",sourceName:"Abu Dhabi Real Estate Centre (ADREC)",sourceUrl:"https://adrec.gov.ae/en/news/press-release-27---adrec-h1-2026-transaction-report",published:"2026-07-17",verified:"2026-08-24",title:{en:"ADREC publishes its H1 2026 transaction report",ar:"مركز أبوظبي العقاري ينشر تقرير معاملات النصف الأول من 2026"},summary:{en:"ADREC’s official release reports the emirate’s first-half transaction activity and regulatory developments. The figures describe a defined reporting period and should not be treated as a forecast or a property-specific return indicator.",ar:"يعرض البيان الرسمي لمركز أبوظبي العقاري نشاط المعاملات والتطورات التنظيمية خلال النصف الأول. تصف الأرقام فترة محددة ولا تمثل توقعاً أو مؤشراً لعائد عقار بعينه."}},
  {id:"dld-rental-2025",sourceName:"Dubai Land Department",sourceUrl:"https://dubailand.gov.ae/en/news-media/dubai-s-rental-sector-records-strong-growth-in-2025-underscoring-market-stability-and-the-strength-of-the-emirate-s-real-estate-ecosystem",published:"2026-02-23",verified:"2026-08-24",title:{en:"DLD releases its review of Dubai’s 2025 rental sector",ar:"دائرة الأراضي والأملاك تنشر مراجعتها لقطاع الإيجارات في دبي لعام 2025"},summary:{en:"The DLD release summarises registered tenancy-contract activity for 2025. It is a market-level retrospective, not a statement about the price, availability or suitability of an individual home.",ar:"يلخص بيان الدائرة نشاط عقود الإيجار المسجلة خلال 2025. وهو استعراض للسوق ولا يحدد سعر منزل بعينه أو توفره أو ملاءمته."}},
];

export function calculateReadingTime(article:InsightArticle,locale:Locale){const copy=article.content[locale];const text=[copy.introduction,...copy.sections.flatMap((section)=>section.paragraphs),...copy.checklist,...copy.considerations.map((item)=>`${item.title} ${item.text}`),copy.limitations,...copy.faq.map((item)=>`${item.question} ${item.answer}`)].join(" ");const words=text.trim().split(/\s+/).length;return Math.max(3,Math.ceil(words/(locale==="ar"?180:220)));}
